### ISSUE TITLE
External vendor load and internal plugin install issues

### ISSUE THREAD

**Issue by NPavie** [claroline/Claroline#1529]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.x.

While trying to install the new home plugin after updating the sources, I had an issue with the VERSION.txt file being not found in the install process.
I also had an issue with the schema search during the loading of a custom resource.

I did a fix for both in SIDPT/Claroline@e146018 if you want to check it.

(I followed the pattern describe in the vendor-shortcut webpack plugins for the external plugin schema search)

**Comment by chalasr** [comment]
Fixed in #1571
