### ISSUE TITLE
[CoreBundle] When a workspace's "Resource to open" points to a file (.doc, .xls etc.), a user can no longer access the workspace

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Claroline#1588]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When a user define's as a "Resource to open" a file (.doc, .xls etc.) then everytime someone opens this workspace, a window shows up proposing to download the file. However the user is not redirected to this workspace. As a result the workspace can no longer be visited by a user (since he can no longer access it).

**Comment by Elorfin** [comment]
En réalité c'est déjà corrigé étant donné que maintenant, on affiche aussi la ressource dans Claroline lorsqu'on propose le téléchargement.
