### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by chalasr** [claroline/Claroline#1602]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.x

Platform Install/Update commands fail on PHP 8:

> [console] Error thrown while running command "claroline:update". Message: "There is no active transaction" ["exception" => PDOException { …},"command" => "claroline:update","message" => "There is no active transaction"]

Related: https://github.com/symfony/symfony/pull/40336
Additionally, we have some deprecation notices triggered by the code that should be fixed as well.

**Comment by maieutiquer** [comment]
I tried to reproduce, but could not get past `composer install --no-dev --optimize-autoloader` in the Dockerfile (Prod mode):

![image](https://user-images.githubusercontent.com/1476049/122665093-f848cc80-d1ad-11eb-998d-bb7333dd9776.png)

Same error with just `composer install` inside the container itself (Dev mode):

![image](https://user-images.githubusercontent.com/1476049/122665163-51186500-d1ae-11eb-8b5a-07fa506ba241.png)
