### ISSUE TITLE
URL : Ouverture automatique

### ISSUE THREAD

**Issue by clarophil** [claroline/Claroline#1610]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.0.5

On utilise la ressource url dans les parcours pour faire des liens vers des vidéos hébergées ailleurs
Il y a quelques mois, on pouvait laisser le mode d'ouverture vide et là on avait juste un bouton Ouvrir
Actuellement, la vidéo (ressource url) s'ouvre automatique.
On souhaite comme avant pouvoir laisser le Mode d'ouverture vide mais ce n'est plus possible, on a un message d'erreur quand on sauve
Ou avoir un mode Ne pas ouvrir automatiquement
![image](https://user-images.githubusercontent.com/895878/110650460-dad19300-81ba-11eb-96d2-e5720c79c42b.png)

**Comment by clarophil** [comment]
ça marche mais l'option ne dit pas Ne pas ouvrir automatiquement
![image](https://user-images.githubusercontent.com/895878/112438567-58afa580-8d48-11eb-91bd-d51799e73fa4.png)

**Comment by LaurentGruber** [comment]
Il fautt vider le cache du navigateur, pour que la traduction soit là.
