### ISSUE TITLE
Permissions lors de la création de rôles

### ISSUE THREAD

**Issue by firepolo** [claroline/Claroline#1653]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Lorsque l'on veut créer un rôle, les permissions sur les outils de bureaux ou d'administration ne s'affiche pas, nous sommes obligé d'enregistrer le rôle pour voir apparaître les persmissions.

![role](https://user-images.githubusercontent.com/1777148/115022118-3af3dd00-9ebd-11eb-922c-7916508b2170.png)

**Comment by LaurentGruber** [comment]
C'est le comportement voulu, si le role n'existe pas, ce n'est pas possible de lui setter des permissions.
