### ISSUE TITLE
Fatal error on administration

### ISSUE THREAD

**Issue by firepolo** [claroline/Claroline#1659]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

L'utilisateur _**irene**_ arrive sur une page blanche si on va sur l'administration. C'est arrivé au moment où je l'ai mise **_manager_** d'une organisation. Je laisse l'utilisateur tel quel si vous voulez regarder.

Aperçu de la console:
![image](https://user-images.githubusercontent.com/1777148/115501391-6f77e800-a273-11eb-9183-fca1e29011ce.png)

Requête HTTP:
![image](https://user-images.githubusercontent.com/1777148/115501448-8585a880-a273-11eb-9e4b-332de24c4d19.png)

**Comment by maieutiquer** [comment]
I've juste retested this on a new installation of 13.0.21 and confirm that it's a critical issue throwing the browser into an infinite loop and consuming 100% CPU core and filling up memory indefinitely

Steps to reproduce:

1. Create a new account from Administration -> Community -> Users
2. Add the **Organizations Administrator** role
3. Log in using that new account
4. Navigate to the Administration from the app-header-dropdown component

Expected result: The application should not hang, not sure what exactly should be the functionality here, either the Administration should not be visible or the user should see an error message or the user should see the expected interface for managing organizations

Actual result: The application hangs in an infinite loop, consuming system resources indefinitely, and we get a "warning" in the Devtools console

![image](https://user-images.githubusercontent.com/1476049/122648382-bbd78b00-d131-11eb-923c-09c7581858c9.png)

![image](https://user-images.githubusercontent.com/1476049/122648389-c85be380-d131-11eb-8a0a-18f3afdf00cc.png)

![image](https://user-images.githubusercontent.com/1476049/122648511-47511c00-d132-11eb-8f56-69331010ae68.png)

![image](https://user-images.githubusercontent.com/1476049/122648475-24266c80-d132-11eb-9365-447edf4a5606.png)
