### ISSUE TITLE
Validation & Quotas par organisation

### ISSUE THREAD

**Issue by firepolo** [claroline/Claroline#1776]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 13.x

### But
Le but de cette fonctionnalité serait qu'une personne du RH lié à une organisation puisse valider ou non l'inscription à une formation des personnes qui appartiennent à la même organisation.

### Fonctionnalité
Le but est d'ajouter un champ de validation (quota) disponible dans l'organisation.
Ce champ de validation (quota) serait le nombre de jour maximum (calculé par le nombre de personnes inscritent à une formation multiplié par la durée en jour contenu dans la **formation**) disponibles pour l'organisation.
Ce quota serait là à titre informatif pour que la personne du RH puisse décider de la validation de l'inscription.

### Implémentation
Pour implémenter ceci, nous pensions créer un plugin dans Claroline pour avoir la possibilité d'avoir des vues propres dans l'administration (Quotas, Validation). Nous aurions aussi la possibilité de rajouter une table dans la base de données nommé ex:"quotas" pour ne pas modifier la structure de base du noyau.

### Vues
Voici les vues que nous pensions implémenter :
- Validation : affiche la liste des inscriptions en attente de validation par organisation avec son quota (utilisé / total).
- Gestion des quotas : Visible par les administrateur, il pourrait modifier le quotas de l'organisation. On aurait aussi la possibilité de créer un nouveau "quota" en choisissant l'organisation lié ainsi que sa valeur.

**Comment by Elorfin** [comment]
We will not implement it.
