### ISSUE TITLE
[Trainings] Cannot delete Workspace or Workspace model from a Training

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#1795]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.1, 13.2

![image](https://user-images.githubusercontent.com/1476049/129526237-be22ba63-766b-489f-a67c-309e9481b76d.png)

**Comment by maieutiquer** [comment]
This issue is still present in 13.2

**Comment by Elorfin** [comment]
Fixed in 13.8
