### ISSUE TITLE
[Trainings] No new lines in session event descriptions in Detailed List

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#1811]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.0.27

Steps:

1. Create event
2. Add a description to the event with new lines (paragraphs)
![image](https://user-images.githubusercontent.com/1476049/130676804-fd5ad8e7-13d1-4352-98bf-f1b971844bb8.png)

3. Save the event

Expected: the new lines should be displayed in the Detailed List view

Actual: new lines are not displayed, everything is on a single line:

![image](https://user-images.githubusercontent.com/1476049/130676847-efcb74f1-b3e3-4650-8460-66454a4219a3.png)

Suggested solution: add new lines to the output (perhaps similar to #1719) and then use:

```css
.data-card-description {
    white-space: pre-line;
}
```

**Comment by LaurentGruber** [comment]
it's not a bug but a feature
