### ISSUE TITLE
[Trainings] Cannot add trainer to session event

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#1812]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.0.27

Steps:

1. Create a course, a session and an event
2. Add yourself as a tutor to the session
3. Go to My Session Events menu
4. Open a session event
5. Try adding yourself as a tutor to the session event

Expected: you should be added as a tutor to the event

Actual: error toast notification with no explaination and a server error in the console's network response:

![image](https://user-images.githubusercontent.com/1476049/130681023-a0def409-ef22-42f3-8872-3feb87867180.png)

Note: even if you remove yourself as a tutor from the session, you still cannot add yourself as a tutor to the session event

**Comment by Elorfin** [comment]
Duplicate https://github.com/claroline/Claroline/issues/1738.
