### ISSUE TITLE
[Trainings] Unable to add a trainer to a Session Event (Séance)

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#1821]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.0.28 (worked in 13.0.26)

Steps:
1. Add a Training with a Session with an Event
2. Open the session's workspace and add a List of Session Events widget (Liste des séances)
3. Click on one of the séances
4. Go to the Participants tab

Expected: We should be able to add a trainer or change/remove the existing one

Actual: we don't see an option to change or remove the existing trainer, or to add a new one

![image](https://user-images.githubusercontent.com/1476049/131585280-86f281f3-407e-4ceb-a749-e8f45cd2e8ca.png)

**Comment by Elorfin** [comment]
This will be fixed by https://github.com/claroline/Claroline/pull/1820.
