### ISSUE TITLE
[Home] Error when clicked on Configure

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#1907]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.0.46,13.1.6

Steps:
1. Navigate to the Home tool
2. Click on the Kebab menu 
3. Click on the Configure option

![image](https://user-images.githubusercontent.com/1476049/138765661-7ffe84e8-2a14-4307-9fbb-bc82161ea9ba.png)

Expected: it should open the Configure modal
Actual: it crashes the application, see screenshot:

![image](https://user-images.githubusercontent.com/1476049/138765951-49bee191-61aa-4cf5-ae3d-f101e9768f15.png)

![image](https://user-images.githubusercontent.com/1476049/138766127-7332dfe1-7556-4b42-b14a-cc7f77c56a56.png)

**Comment by maieutiquer** [comment]
I found that it works if I modify this line, I hope that helps debugging:

![image](https://user-images.githubusercontent.com/1476049/151406153-2e5e6711-7f85-493d-a26f-6e8586a7b84f.png)

**Comment by LaurentGruber** [comment]
Je ne reproduis pas sur une 13.1.6 de prod

**Comment by maieutiquer** [comment]
Thanks for taking a look, it's broken in our Prod and it's always reproducible on a new installation from scratch
You could also reproduce it here: https://www.cep-test.ch/
Steps:
1. Log in with your admin account
2. Navigate to the homepage
3. Click on Voir plus d'actions -> Configurer
