### ISSUE TITLE
[Core] claroline:update broken in 13.1

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#1919]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.1 (works in 13.0)

Steps (DEV):
1. Install Claroline branch 13.1 from scratch in DEV mode (e.g. using `docker-compose -f docker-compose.dev.yml up`
2. Run `php bin/console claroline:update --env=dev -vvv` (if using Docker, first run `docker exec -it claroline-web bash`)

Steps (PROD):
1. Install Claroline branch 13.1 from scratch in PROD mode (e.g. using `docker-compose up`
2. Run `php bin/console claroline:update -vvv` (if using Docker, first run `docker exec -it claroline-web bash`)

Expected (and currently works correctly in  branch 13.0 for both PROD and DEV):
The command should run the updater and rebuild the translations and themes

Actual (in 13.1):

CRITICAL  [console] Error thrown while running command "claroline:update -vvv". Message: "
An exception occurred while executing 'INSERT INTO claro_template (system, entity_name, uuid, claro_template_type) VALUES (?, ?, ?, ?)' with params [1, "Claroline Connect", "f32edaf7-2b32-45c8-9f0d-79d12b5b90a6", 1]:\n
\n
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system, entity_name, uuid, claro_template_type) VALUES (1, 'Claroline Connect', ' at line 1

In PDOStatement.php line 117:

  [PDOException (42000)]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system, entity_name, uuid, claro_template_type) VALUES (1, 'Claroline Connect', ' at line 1

![image](https://user-images.githubusercontent.com/1476049/139709147-02a28834-c65b-47b6-9188-8af4a783d78a.png)

![image](https://user-images.githubusercontent.com/1476049/139710740-a458ab30-88ac-4c8c-886b-07d3f1fb9275.png)

![image](https://user-images.githubusercontent.com/1476049/139703347-dd55c357-a856-459f-825f-abeac91e41b0.png)

This is blocking us from upgrading the system and from rebuilding translations

**Comment by maieutiquer** [comment]
Could this be related to the conditional fields?
Perhaps something was reworked in 13.0, possibly in the `architecture` branch, and the conditional fields did not get updated? (or I might be completely wrong)

**Comment by LaurentGruber** [comment]
la 13.1 est une branche de dev, qui n'est pas encore prete pour la production... Ce n'est pas nécessaire de faire de ticket spécifique à cette version tant que c'est la branche de dev.

**Comment by maieutiquer** [comment]
This issue is still there and it's still preventing us from testing the conditional fields properly, could someone take a look?

**Comment by Elorfin** [comment]
Issue is fixed by : https://github.com/claroline/Claroline/commit/38cce80338497e6646e413e57eb15d0ba4f2f802.
You still get errors because it has partially broken your DB, which I can not fix. You need to restore your DB and redo an upgrade.

**Comment by maieutiquer** [comment]
Thanks, but I'm doing a clean install from scratch with no database and the first `claroline:install` works, but subsequent runs fail - do I need to "restore" my DB before each upgrade and how do I do this? Can it be automated?

**Comment by Elorfin** [comment]
I don't reproduce it. Install and next upgrades are ok on my env.

**Comment by maieutiquer** [comment]
Not sure what should be my env, I tried downgrading to PHP 7.4 and I tried removing the `composer delete-cache` after the initial install, but I got the same result

I found that if I uncomment the following two lines, the update starts passing:
![image](https://user-images.githubusercontent.com/1476049/143236971-9f48c801-3792-42e4-b985-feff56e71331.png)

I guess this should not be the correct approach, but it might give a hint about the source of the issue

**Comment by maieutiquer** [comment]
Thanks for having looked into it, but now it seems that user creation is broken (clean install from scratch):

![image](https://user-images.githubusercontent.com/1476049/143415496-5e70f9bf-9064-4eaf-abbb-9ce3946ee5aa.png)

And when we run claroline:install a second time, we get the following error:

![image](https://user-images.githubusercontent.com/1476049/143415684-f59b9162-bc0a-4bcc-b4eb-a86069eeb649.png)
