### ISSUE TITLE
Table 'claroline.claro_widget_progression' doesn't exist

### ISSUE THREAD

**Issue by Pixman** [claroline/Claroline#1969]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.0.48

Bonjour,
j'essaie d'ajouter le widget "Progression" sur mon espace d'activité.
A l'enregistrement j'ai une erreur.

Voici le contenu du message d'erreur : 
```
message: "An exception occurred while executing 'SELECT t0.level_max AS level_max_1, t0.id AS id_2, t0.widgetInstance_id AS widgetInstance_id_3 FROM claro_widget_progression t0 WHERE t0.widgetInstance_id = ? LIMIT 1' with params [null]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'claroline.claro_widget_progression' doesn't exist"
```

Je n'ai pas constaté d'erreur pendant la mise à jour de la BDD, lors de la montée de version.

Merci pour vos pistes de résolution.

**Comment by Elorfin** [comment]
Bonjour,
Il s'agit d'un ancien widget qui aurait du disparaître car il est non fonctionnel.
Dans la 13.1, il y a de nouvelles listes sur les évaluations pour le Widget Liste qui permettent d'afficher les même informations.

Nous allons supprimer le widget pour éviter les confusions.

**Comment by Pixman** [comment]
Merci beaucoup pour votre retour😉
