### ISSUE TITLE
[Registration] Cannot select an organization from the hierarchy picker

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#1984]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.1.2, 13.1.4

Steps:
1. Install Claroline 13.1.4 from scratch
2. Create at least one new organization in addition to the default organization, for example:
![image](https://user-images.githubusercontent.com/1476049/146095945-34379c7a-9f74-478b-828d-e37e205d2b65.png)
3. Check "Enable self-registration" from Administration -> Community -> Parameters
4. Add a custom tab, section and field of type Organization in Mode "List":
![image](https://user-images.githubusercontent.com/1476049/146095343-46bd069c-5fec-490f-896c-badd4ffe49a2.png)
5. Log out and create a new non-admin account using the "Create an account" button
(note: you'll need to remove the `redux-freeze` middleware, otherwise the "Validate my registration" button will not work, see #1964 )
6. Log in using the new non-admin account
7. Go to "My account" in Edit mode and try selecting an organization

Expected: you should be able to select an organization and its children, like this (an administrator can see all organizations):
![image](https://user-images.githubusercontent.com/1476049/146095600-77090974-0516-4411-856e-9fcc2ccb93d2.png)

Actual: you cannot see any organization, only the default one:
![image](https://user-images.githubusercontent.com/1476049/146096160-d1eeb6a2-59ab-4f96-ab09-97ee14a670fe.png)

This is blocking us from testing the custom fields functionality and is urgent for us, is there a temporary workaround that we can try implementing in a temporary branch until this is fixed?

**Comment by Elorfin** [comment]
Organizations must be public to appear to users who are not registered in it.
