### ISSUE TITLE
[Espace d'activité] Impossible de créer un espace d'activité à partir d'un modèle

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#2001]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.1.2

Steps:
1. Create an empty model (with no resources), but with parameters for community rights
2. Try to create a workspace from that model

![image](https://user-images.githubusercontent.com/1476049/148968313-8cf907cc-5781-4896-822a-2f7e1ff93ec0.png)

**Comment by LaurentGruber** [comment]
ça été corrigé dans la 13.1.3 ou 13.1.4 je ne sais plus
