### ISSUE TITLE
[Trainings] Session invitation dates are incorrect because of timezones

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#2019]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.1.6

When we add a user to a session, they receive a confirmation e-mail with incorrect time because of timezone issues

**Comment by maieutiquer** [comment]
Our temporary solution is to hardcode `->setTimezone(new \DateTimeZone('Europe/Zurich'))` before formatting:
https://github.com/konsept-ch/Claroline/pull/48/files

The issue seems to be that the text is sent directly to the Messages and there's no JS to parse the timezone, so it's up to PHP to pass it correctly

Not sure how this should be handled more generally, perhaps we should be able to set the timezone offset somehow or maybe PHP should read it from the request params (passed from JS to the API using a param or some other way)?

**Comment by Elorfin** [comment]
Fixed in 13.8
