### ISSUE TITLE
[corebundle] administration > communauté - erreur car dossier archive manquant

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Claroline#2191]
Après une nouvelle install quand on va dans administration > communauté j'ai une erreur 500 : 
DirectoryIterator::__construct(/home/demo/www/files/archives): failed to open dir: No such file or directory

Si je crée le dossier, plus de souci.

**Comment by Elorfin** [comment]
La feature en question a été supprimée (archive de la DB au format csv).
