### ISSUE TITLE
[Security, Community, Trainings] Regular user can edit/delete sessions and events if he's an Organization Manager

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#2215]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.5.14

This is an urgent security production issue that's causing real problems

Steps:
1. Install Claroline from scratch
2. Create a new user
3. Add this user as a Manager to the default organization
4. Create a training with a Session and a Session Event
5. Login with the new user

Expected: the new user should not be able to edit and delete the Session and the Event
Actual: the user is able to edit and delete the Session and the Event

![image](https://user-images.githubusercontent.com/1476049/191924978-4eb17501-a413-4865-bc07-2cf26075819c.png)

![image](https://user-images.githubusercontent.com/1476049/191925018-722eb838-d147-468d-af7b-044ab78e49ac.png)

**Comment by LaurentGruber** [comment]
Ce n'est ni un bug, ni une faille c'est le comportement voulu. Les gestionnaires d'organisation peuvent gérer tous ce qui touche à leur organisation vu qu'ils en sont gestionnaire.
