### ISSUE TITLE
[Community] push group roles to the user entity

### ISSUE THREAD

**Issue by Elorfin** [claroline/Claroline#2259]
For now, each time we need to get the user roles, we need to fetch the roles from its groups too.

When adding/removing a role to a group we should directly modify the user role list.

**Comment by maieutiquer** [comment]
Not sure if I understand correctly, but what if a user already had a role before being added to a group that grants this role and then we remove that user from that group - is the role going to be removed?
For example, if a group "Admins" initially has the "admin" role and a user initially has the "admin" role, then that user gets added to the "Admins" group and then removed from the "Admins" group, is he still going to have the "admin" role?
