### ISSUE TITLE
pgsql incompatibilitie(s)

### ISSUE THREAD

**Issue by dgeo** [claroline/Claroline#614]
In those files:
* ./vendor/claroline/core-bundle/Claroline/CoreBundle/Migrations/pdo_pgsql/Version20131010151055.php
* ./vendor/claroline/
core-bundle/Claroline/CoreBundle/Migrations/pdo_pgsql/Version20130913134332.php
* ./vendor/claroline/rss-reader-bundle/Claroline/RssReaderBundle/Migrations/pdo_pgsql/Version20130925173308.php
* ./vendor/claroline/rss-reader-bundle/Claroline/RssReaderBundle/Migrations/pdo_pgsql/Version20130925173308.php

There are four 'DROP CONSTRAINT IF EXISTS' that won't work under postgresql (8.4 at least)
```
  [Doctrine\DBAL\DBALException]                                                          
  An exception occurred while executing '                                                
              ALTER TABLE claro_widget_home_tab_config                                   
              DROP CONSTRAINT IF EXISTS FK_D48CC23EFBE885E2                              
          ':                                                                             
                                                                                         
  SQLSTATE[42601]: Syntax error: 7 ERREUR:  erreur de syntaxe sur ou près de « EXISTS »  
  LINE 3:             DROP CONSTRAINT IF EXISTS FK_D48CC23EFBE885E2
```

Didnt't check forward to see if there are others…

**Comment by ngodfraind** [comment]
We're not supporting pgsql for now. Everyone works on Mysql/MariaDb. Doctrine is supposed to be able to handle it, but in practice, it doesn't work like that.
