### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by FabriceC01** [claroline/Claroline#619]
Hello there,
I just tried to install claroline connect on my site hosted by 1and1 and I get an error message that I do not know deal:

Fatal error: Out of memory (Allocated 40632320) (tried to allocate 36 bytes) in /homepages/13/d215333239/htdocs/techno/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 760

I have not found a help forum about this release as it existed on earlier so I tried here.

I said that the configuration checks were well past:

PHP configuration is correct.
Your PHP configuration settings are correct.
PHP extensions extension ffmpeg should be installed and enabled.
A PHP accelerator (like APC or XCache) should be installed and enabled (highly recommended).
File permissions configuration is correct.

thank you for your help

Fabrice

**Comment by petermayer-la** [comment]
I've the same issue. Here the protocol. Anybody managed to solve that?
Also I've uploaded what it says before I start the installation.
@jeremylievens did you solve it yet?
@ngodfraind do you have any idea how to solve?
I've 128mb memory limit. Do I really need 256? It would be 5€+/month at my current provider

[ERROR] An exception has been thrown during installation
Message: An exception occurred while executing 'INSERT INTO claro_role (name, translation_key, is_read_only, type, maxUsers, workspace_id) VALUES (?, ?, ?, ?, ?, ?)' with params ["ROLE_USER", "user", 1, 1, null, null]:

Detailed installation log:
Clearing the cache...
Installing assets using the symlink option
Installing assets for Innova\AngularJSBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/innovaangularjs
Installing assets for Innova\AngularUITranslationBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/innovaangularuitranslation
Installing assets for Icap\PortfolioBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/icapportfolio
Installing assets for Icap\NotificationBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/icapnotification
Installing assets for Claroline\Bundle\FrontEndBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/frontend
Installing assets for Claroline\CoreBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinecore
Installing assets for Claroline\ImagePlayerBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/clarolineimageplayer
Installing assets for Claroline\PdfPlayerBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinepdfplayer
Installing assets for Claroline\VideoPlayerBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinevideoplayer
Installing assets for Claroline\WebResourceBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinewebresource
Installing assets for Icap\WikiBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/icapwiki
Installing assets for Claroline\ActivityToolBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/clarolineactivitytool
Installing assets for Claroline\AnnouncementBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/clarolineannouncement
Installing assets for Claroline\ForumBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/clarolineforum
Installing assets for Claroline\RssReaderBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinerssreader
Installing assets for Claroline\ScormBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinescorm
Installing assets for Icap\BlogBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/icapblog
Installing assets for Icap\LessonBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/icaplesson
Installing assets for Icap\DropzoneBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/icapdropzone
Installing assets for UJM\ExoBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/ujmexo
Installing assets for Innova\AngularUITreeBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/innovaangularuitree
Installing assets for Innova\AngularUITinyMCEBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/innovaangularuitinymce
Installing assets for Innova\AngularUIResourcePickerBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/innovaangularuiresourcepicker
Installing assets for Innova\AngularUIPageslideBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/innovaangularuipageslide
Installing assets for Innova\AngularUIBootstrapBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/innovaangularuibootstrap
Installing assets for Innova\PathBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/innovapath
Installing assets for Symfony\Bundle\FrameworkBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/framework
Installing assets for Bazinga\ExposeTranslationBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/bazingaexposetranslation
Installing assets for Zenstruck\Bundle\FormBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/zenstruckform
Installing assets for WhiteOctober\PagerfantaBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/whiteoctoberpagerfanta
Installing assets for Stfalcon\Bundle\TinymceBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/stfalcontinymce
Installing assets for Nelmio\ApiDocBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/nelmioapidoc
Installing assets for FOS\JsRoutingBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/../web/bundles/fosjsrouting
Installing the platform from kernel...
Checking database connection...
Checking acl tables are initialized...
Aborting: The table with name 'claroline_connect.acl_classes' already exists.
Creating public sub-directories...
Installing ClarolineCoreBundle...
Launching pre-installation actions...
Executing migrations...
Loading required fixtures...
[ERROR] An exception has been thrown during installation
Message: An exception occurred while executing 'INSERT INTO claro_role (name, translation_key, is_read_only, type, maxUsers, workspace_id) VALUES (?, ?, ?, ?, ?, ?)' with params ["ROLE_USER", "user", 1, 1, null, null]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ROLE_USER' for key 'UNIQ_317774715E237E06'
Trace: #0 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(167): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(PDOException), 'INSERT INTO cla...', Array)
#1 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(279): Doctrine\DBAL\Statement->execute()
#2 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(952): Doctrine\ORM\Persisters\BasicEntityPersister->executeInserts()
#3 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(335): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#4 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(389): Doctrine\ORM\UnitOfWork->commit(NULL)
#5 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/cache/prod/jms_diextra/doctrine/EntityManager_54b29345eb87a.php(402): Doctrine\ORM\EntityManager->flush(NULL)
#6 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/doctrine/common/lib/Doctrine/Common/Persistence/ObjectManagerDecorator.php(98): EntityManager54b29345eb87a_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager->flush()
#7 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/claroline/core-bundle/Claroline/CoreBundle/Persistence/ObjectManager.php(83): Doctrine\Common\Persistence\ObjectManagerDecorator->flush()
#8 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/claroline/core-bundle/Claroline/CoreBundle/Persistence/ObjectManager.php(110): Claroline\CoreBundle\Persistence\ObjectManager->flush()
#9 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/claroline/core-bundle/Claroline/CoreBundle/DataFixtures/Required/LoadRequiredFixturesData.php(70): Claroline\CoreBundle\Persistence\ObjectManager->endFlushSuite()
#10 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php(121): Claroline\CoreBundle\DataFixtures\Required\LoadRequiredFixturesData->load(Object(Doctrine\ORM\EntityManager))
#11 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php(83): Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load(Object(Doctrine\ORM\EntityManager), Object(Claroline\CoreBundle\DataFixtures\Required\LoadRequiredFixturesData))
#12 [internal function]: Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closure}(Object(Doctrine\ORM\EntityManager))
#13 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(243): call_user_func(Object(Closure), Object(Doctrine\ORM\EntityManager))
#14 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/app/cache/prod/jms_diextra/doctrine/EntityManager_54b29345eb87a.php(32): Doctrine\ORM\EntityManager->transactional(Object(Closure))
#15 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php(85): EntityManager54b29345eb87a_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager->transactional(Object(Closure))
#16 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/claroline/installation-bundle/Claroline/InstallationBundle/Fixtures/FixtureLoader.php(57): Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute(Array, true)
#17 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/claroline/installation-bundle/Claroline/InstallationBundle/Manager/InstallationManager.php(66): Claroline\InstallationBundle\Fixtures\FixtureLoader->load(Object(Claroline\CoreBundle\ClarolineCoreBundle), 'DataFixtures/Re...')
#18 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Installation/PlatformInstaller.php(101): Claroline\InstallationBundle\Manager\InstallationManager->install(Object(Claroline\CoreBundle\ClarolineCoreBundle), true)
#19 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(111): Claroline\CoreBundle\Library\Installation\PlatformInstaller->installFromKernel(false)
#20 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(65): Claroline\WebInstaller\Installer->launchInstaller(Object(appProdProjectContainer), Object(Symfony\Component\Console\Output\StreamOutput))
#21 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Controller.php(237): Claroline\WebInstaller\Installer->install()
#22 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Kernel.php(64): Claroline\WebInstaller\Controller->installSubmitStep()
#23 /var/www/vhosts/h141866.server04.campusspeicher.de/clarolineconnect.h141866.server04.campusspeicher.de/web/install.php(14): Claroline\WebInstaller\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#24 {main}
![screen shot 2015-01-11 at 16 12 01](https://cloud.githubusercontent.com/assets/1744718/5695637/7dea1b72-99ad-11e4-8523-3ca3586b2655.png)

**Comment by clarophil** [comment]
Can you try the new release 4.1.0 ?
http://dist.claroline.net/

**Comment by petermayer-la** [comment]
hi, thanks for your reply. I did. I didn't succed with this version either.
See attached the screenshot.
However I've only 128MB of Memory. Do I really need 256?

Installation failure
Installation has failed. Please report this incident.

Detailed installation log

Clearing the cache...
Installing assets as symlinks
Installing assets for Innova\AngularJSBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/innovaangularjs
Installing assets for Claroline\Bundle\FrontEndBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/frontend
Installing assets for Claroline\CoreBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinecore
Installing assets for Claroline\ActivityToolBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolineactivitytool
Installing assets for Claroline\AnnouncementBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolineannouncement
Installing assets for Claroline\ForumBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolineforum
Installing assets for Claroline\ImagePlayerBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolineimageplayer
Installing assets for Claroline\PdfPlayerBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinepdfplayer
Installing assets for Claroline\RssReaderBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinerssreader
Installing assets for Claroline\VideoPlayerBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinevideoplayer
Installing assets for Claroline\WebResourceBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinewebresource
Installing assets for Claroline\SurveyBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinesurvey
Installing assets for Claroline\TeamBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolineteam
Installing assets for Icap\NotificationBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/icapnotification
Installing assets for Icap\WikiBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/icapwiki
Installing assets for Icap\LessonBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/icaplesson
Installing assets for Claroline\ScormBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/clarolinescorm
Installing assets for UJM\ExoBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/ujmexo
Installing assets for Icap\BlogBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/icapblog
Installing assets for Symfony\Bundle\FrameworkBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/framework
Installing assets for Bazinga\Bundle\JsTranslationBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/bazingajstranslation
Installing assets for Zenstruck\Bundle\FormBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/zenstruckform
Installing assets for WhiteOctober\PagerfantaBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/whiteoctoberpagerfanta
Installing assets for Stfalcon\Bundle\TinymceBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/stfalcontinymce
Installing assets for FOS\JsRoutingBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/fosjsrouting
Installing assets for Nelmio\ApiDocBundle into /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/../web/bundles/nelmioapidoc
Installing the platform from kernel...
Checking database connection...
Checking acl tables are initialized...
Aborting: The table with name 'claroline_connect.acl_classes' already exists.
Creating public sub-directories...
Installing ClarolineCoreBundle...
Launching pre-installation actions...
Executing migrations...
Loading required fixtures...
[ERROR] An exception has been thrown during installation
Message: An exception occurred while executing 'INSERT INTO claro_role (name, translation_key, is_read_only, type, maxUsers, workspace_id) VALUES (?, ?, ?, ?, ?, ?)' with params ["ROLE_USER", "user", 1, 1, null, null]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ROLE_USER' for key 'UNIQ_317774715E237E06'
Trace: #0 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(172): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO cla...', Array)
#2 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(279): Doctrine\DBAL\Statement->execute()
#3 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(966): Doctrine\ORM\Persisters\BasicEntityPersister->executeInserts()
#4 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(335): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(389): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/cache/prod/jms_diextra/doctrine/EntityManager_54b5b9e5713ae.php(402): Doctrine\ORM\EntityManager->flush(NULL)
#7 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/common/lib/Doctrine/Common/Persistence/ObjectManagerDecorator.php(98): EntityManager54b5b9e5713ae_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager->flush()
#8 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/core-bundle/Claroline/CoreBundle/Persistence/ObjectManager.php(84): Doctrine\Common\Persistence\ObjectManagerDecorator->flush()
#9 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/core-bundle/Claroline/CoreBundle/Persistence/ObjectManager.php(111): Claroline\CoreBundle\Persistence\ObjectManager->flush()
#10 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/core-bundle/Claroline/CoreBundle/DataFixtures/Required/Data/LoadPlatformRolesData.php(40): Claroline\CoreBundle\Persistence\ObjectManager->endFlushSuite()
#11 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/core-bundle/Claroline/CoreBundle/DataFixtures/Required/LoadRequiredFixturesData.php(91): Claroline\CoreBundle\DataFixtures\Required\Data\LoadPlatformRolesData->load(Object(Claroline\CoreBundle\Persistence\ObjectManager))
#12 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php(121): Claroline\CoreBundle\DataFixtures\Required\LoadRequiredFixturesData->load(Object(Doctrine\ORM\EntityManager))
#13 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php(83): Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load(Object(Doctrine\ORM\EntityManager), Object(Claroline\CoreBundle\DataFixtures\Required\LoadRequiredFixturesData))
#14 [internal function]: Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closure}(Object(Doctrine\ORM\EntityManager))
#15 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(243): call_user_func(Object(Closure), Object(Doctrine\ORM\EntityManager))
#16 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/app/cache/prod/jms_diextra/doctrine/EntityManager_54b5b9e5713ae.php(32): Doctrine\ORM\EntityManager->transactional(Object(Closure))
#17 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php(85): EntityManager54b5b9e5713ae_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager->transactional(Object(Closure))
#18 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/installation-bundle/Claroline/InstallationBundle/Fixtures/FixtureLoader.php(57): Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute(Array, true)
#19 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/installation-bundle/Claroline/InstallationBundle/Manager/InstallationManager.php(66): Claroline\InstallationBundle\Fixtures\FixtureLoader->load(Object(Claroline\CoreBundle\ClarolineCoreBundle), 'DataFixtures/Re...')
#20 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Installation/PlatformInstaller.php(101): Claroline\InstallationBundle\Manager\InstallationManager->install(Object(Claroline\CoreBundle\ClarolineCoreBundle), true)
#21 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(113): Claroline\CoreBundle\Library\Installation\PlatformInstaller->installFromKernel(false)
#22 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(65): Claroline\WebInstaller\Installer->launchInstaller(Object(appProdProjectContainer), Object(Symfony\Component\Console\Output\StreamOutput))
#23 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Controller.php(238): Claroline\WebInstaller\Installer->install()
#24 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Kernel.php(64): Claroline\WebInstaller\Controller->installSubmitStep()
#25 /var/www/vhosts/h141866.server04.campusspeicher.de/claroline-new.h141866.server04.campusspeicher.de/web/install.php(13): Claroline\WebInstaller\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#26 {main}

**Comment by clarophil** [comment]
Could you try to remove your database before reinstall ?

**Comment by petermayer-la** [comment]
I did of course. It's always a new created one. Or how do you mean?

**Comment by petermayer-la** [comment]
@clarophil any news on that? is the 256mb memory the solution?

**Comment by clarophil** [comment]
No I don't think that it will help you.
Do you try the command line installation ?

**Comment by petermayer-la** [comment]
no i haven't tried the command line installation yet.
