### ISSUE TITLE
Can't create users with import CVS 

### ISSUE THREAD

**Issue by clarophil** [claroline/Claroline#637]
Warning: file_get_contents(/home/precc/app/../templates/default/manifest.yml): failed to open stream: No such file or directory in /home/precc/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Transfert/Resolver.php on line 31

Catchable fatal error: Argument 2 passed to Claroline\CoreBundle\Manager\TransfertManager::setImporters() must be of the type array, null given, called in /home/precc/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/TransfertManager.php on line 144 and defined in /home/precc/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/TransfertManager.php on line 305

**Comment by ngodfraind** [comment]
I assume we fixed it a long time ago.
