### ISSUE TITLE
How to configure Claroline under nginx?

### ISSUE THREAD

**Issue by unixfox** [claroline/Claroline#639]
_If you talk French, please use this language, I am Belgian._

I use nginx to host claroline but unfortunately the URL rewriting does not work with nginx.
What configuration should I use to run Claroline under nginx?

---------------------------------------

J'utilise nginx pour héberger claroline mais malheureusement la réécriture url ne fonctionne pas sous nginx puisque nginx n'utilise pas les .htaccess.
Quelle configuration devrais-je utiliser pour faire fonctionner Claroline sous nginx ?

**Comment by ngodfraind** [comment]
Bonjour,

Avec beaucoup de retard - désolé, je suis en train de tout nettoyer.

nginx + php5-fpm.

 location / {
        include /etc/nginx/naxsi.rules;
        # try to serve file directly, fallback to rewrite
        try_files $uri @rewriteapp;
    }

    location @rewriteapp {
        # rewrite all to app.php
        rewrite ^(.*)$ /app.php/$1 last;
    }

    location ~ ^/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass unix:/var/run/php5-fpm.phpfpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;
    }
