### ISSUE TITLE
Can't edit users properties if no personnal workspace

### ISSUE THREAD

**Issue by clarophil** [claroline/Claroline#646]
ONLY for user without personnal workspace
In User Administration / Modify
Change firstname failed

Catchable fatal error: Argument 1 passed to Claroline\CoreBundle\Manager\WorkspaceManager::rename() must be an instance of Claroline\CoreBundle\Entity\Workspace\Workspace, null given, called in /var/www/clacogit/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/UserManager.php on line 178 and defined in /var/www/clacogit/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/WorkspaceManager.php on line 144

**Comment by ngodfraind** [comment]
fixed by claroline/corebundle#988
