### ISSUE TITLE
Calendar - user can change item without permission

### ISSUE THREAD

**Issue by clarophil** [claroline/Claroline#647]
Collaborator can only see the items in the calendar 
![image](https://cloud.githubusercontent.com/assets/895878/5629651/271e4ad4-95b6-11e4-8c32-6525b175f42d.png)
But he can also modify an item without permission 
![image](https://cloud.githubusercontent.com/assets/895878/5629673/5611ec24-95b6-11e4-8e21-db881ed760e1.png)

**Comment by ngodfraind** [comment]
I'm not able to reproduce the issue.

2015-01-06 15:11 GMT+01:00 clarophil <notifications@github.com>:

> Collaborator can only see the items in the calendar
> [image: image]
> <https://cloud.githubusercontent.com/assets/895878/5629651/271e4ad4-95b6-11e4-8c32-6525b175f42d.png>
> But he can also modify an item without permission
> [image: image]
> <https://cloud.githubusercontent.com/assets/895878/5629673/5611ec24-95b6-11e4-8e21-db881ed760e1.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/647>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
The calendar will be removed from the CoreBundle
