### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by jbsselim** [claroline/Claroline#650]
I dont really know how to report it, i'll just write it 

Installation has failed. Please report this incident.

Detailed installation log

Clearing the cache...
Installing assets using the hard copy option
Installing assets for Innova\AngularJSBundle into C:/wamp/www/claroline/app/../web/bundles/innovaangularjs
Installing assets for Innova\AngularUITranslationBundle into C:/wamp/www/claroline/app/../web/bundles/innovaangularuitranslation
Installing assets for Icap\PortfolioBundle into C:/wamp/www/claroline/app/../web/bundles/icapportfolio
Installing assets for Icap\NotificationBundle into C:/wamp/www/claroline/app/../web/bundles/icapnotification
Installing assets for Claroline\Bundle\FrontEndBundle into C:/wamp/www/claroline/app/../web/bundles/frontend
[ERROR] An exception has been thrown during installation
Message: Failed to remove directory "C:/wamp/www/claroline/app/../web/bundles/frontend\jquery\jquery-ui-1.9.2.custom\css\ui-lightness".
Trace: #0 C:\wamp\www\claroline\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php(142): Symfony\Component\Filesystem\Filesystem->remove(Object(FilesystemIterator))
#1 C:\wamp\www\claroline\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php(142): Symfony\Component\Filesystem\Filesystem->remove(Object(FilesystemIterator))
#2 C:\wamp\www\claroline\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php(142): Symfony\Component\Filesystem\Filesystem->remove(Object(FilesystemIterator))
#3 C:\wamp\www\claroline\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php(142): Symfony\Component\Filesystem\Filesystem->remove(Object(FilesystemIterator))
#4 C:\wamp\www\claroline\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand.php(94): Symfony\Component\Filesystem\Filesystem->remove('C:/wamp/www/cla...')
#5 C:\wamp\www\claroline\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php(241): Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#6 C:\wamp\www\claroline\vendor\claroline\core-bundle\Claroline\CoreBundle\Library\Installation\Refresher.php(70): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#7 C:\wamp\www\claroline\vendor\claroline\web-installer\lib\Claroline\WebInstaller\Installer.php(64): Claroline\CoreBundle\Library\Installation\Refresher->installAssets()
#8 C:\wamp\www\claroline\vendor\claroline\web-installer\lib\Claroline\WebInstaller\Controller.php(237): Claroline\WebInstaller\Installer->install()
#9 C:\wamp\www\claroline\vendor\claroline\web-installer\lib\Claroline\WebInstaller\Kernel.php(64): Claroline\WebInstaller\Controller->installSubmitStep()
#10 C:\wamp\www\claroline\web\install.php(13): Claroline\WebInstaller\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#11 {main}

**Comment by clarophil** [comment]
Do you try with 4.1.6 version ?  http://dist.claroline.net/

**Comment by jbsselim** [comment]
nope sorry i'll try, thanks for answering

**Comment by jbsselim** [comment]
Warning: imagecreatefrompng(C:/wamp/www/claroline1/app\..\web\bundles/clarolinecore/images/resources/icons/res_default.png): failed to open stream: No such file or directory in C:\wamp\www\claroline1\vendor\claroline\core-bundle\Claroline\CoreBundle\Library\Utilities\ThumbnailCreator.php on line 176

Warning: imagecreatefrompng(C:/wamp/www/claroline1/app\..\web\bundles\clarolinecore\images\resources\icons\shortcut-black.png): failed to open stream: No such file or directory in C:\wamp\www\claroline1\vendor\claroline\core-bundle\Claroline\CoreBundle\Library\Utilities\ThumbnailCreator.php on line 182

Warning: imagesavealpha() expects parameter 1 to be resource, boolean given in C:\wamp\www\claroline1\vendor\claroline\core-bundle\Claroline\CoreBundle\Library\Utilities\ThumbnailCreator.php on line 183

Warning: imagesy() expects parameter 1 to be resource, boolean given in C:\wamp\www\claroline1\vendor\claroline\core-bundle\Claroline\CoreBundle\Library\Utilities\ThumbnailCreator.php on line 184

Warning: imagesy() expects parameter 1 to be resource, boolean given in C:\wamp\www\claroline1\vendor\claroline\core-bundle\Claroline\CoreBundle\Library\Utilities\ThumbnailCreator.php on line 184

These are the errors with the 4.1.6 version

**Comment by jbsselim** [comment]
Do you know where does these error come from?

**Comment by ngodfraind** [comment]
They're warning because gd and ffmpeg extensions are missing. It's not
important unless you want video/images thumbnails.

2015-02-02 12:59 GMT+01:00 jbsselim <notifications@github.com>:

> Do you know where does these error come from?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/650#issuecomment-72445654>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by jbsselim** [comment]
Ok but is it normal that i can't find a ffmpeg extensions for php5.5?i'm on windows 7
