### ISSUE TITLE
Error installing Claroline with command line

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#655]
Ive followed the steps as for my previous (successful) installation of Claroline 
https://github.com/claroline/Claroline/#user-content-development-installation

But when i arrive at the step 
```composer update --prefer-source```

I have this error 
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Script Claroline\BundleRecorder\ScriptHandler::prepareUninstallOperation handling the pre-package-uninstall event terminated with an exception
                                                       
  [ErrorException]                                                                                                     
  Argument 1 passed to Claroline\BundleRecorder\ScriptHandler::getRecorder() must be an instance of Composer\Script\Event, instance of Composer\Script\PackageEvent given, called in /home/olivier/www/claroline4-v3/Claroline/vendor/claroline/bundle-recorder/Claroline/BundleRecorder/ScriptHandler.php on line 79 and defined 
```

This happened with the latest version of this repository (01/03/2015)

Is this a problem with the new packages or is there an extra step to do now but that is not updated in the documentation yet ?

**Comment by ngodfraind** [comment]
It happens with the last version of composer. You gave to downgrade
composer or wait we fix the uses (I'll do it today).

2015-03-01 16:34 GMT+01:00 stmolivier <notifications@github.com>:

> Ive followed the steps as for my previous (successful) installation of
> Claroline
>
> https://github.com/claroline/Claroline/#user-content-development-installation
>
> But when i arrive at the step
> composer update --prefer-source
>
> I have this error
>
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Script Claroline\BundleRecorder\ScriptHandler::prepareUninstallOperation handling the pre-package-uninstall event terminated with an exception
>
>   [ErrorException]
>   Argument 1 passed to Claroline\BundleRecorder\ScriptHandler::getRecorder() must be an instance of Composer\Script\Event, instance of Composer\Script\PackageEvent given, called in /home/olivier/www/claroline4-v3/Claroline/vendor/claroline/bundle-recorder/Claroline/BundleRecorder/ScriptHandler.php on line 79 and defined
>
> This happened with the latest version of this repository (01/03/2015)
>
> Is this a problem with the new packages or is there an extra step to do
> now but that is not updated in the documentation yet ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/655>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
yes, i've just seen the messsge on Google group claco-dev about it. The trick works.

**Comment by ngodfraind** [comment]
I think it is a composer bug introduced by this commit
https://github.com/composer/composer/commit/3efed220a6c9fd6e4a13ea806879e124941c9fc7#diff-c2d55809c84c01df1b142806afcc20de
.



2015-03-02 10:39 GMT+01:00 stmolivier <notifications@github.com>:

> yes, i've just seen the messsge on Google group claco-dev about it. The
> trick works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/655#issuecomment-76682494>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
Ok it's not a bug, but PackageEvent parent's class changed. The same goes
for a lot of other stuff wich is why everything broke.
I can fix it now.

2015-03-02 16:14 GMT+01:00 Godfraind Nicolas <nicolas.godfraind@gmail.com>:

> I think it is a composer bug introduced by this commit
> https://github.com/composer/composer/commit/3efed220a6c9fd6e4a13ea806879e124941c9fc7#diff-c2d55809c84c01df1b142806afcc20de
> .
>
>
>
> 2015-03-02 10:39 GMT+01:00 stmolivier <notifications@github.com>:
>
>> yes, i've just seen the messsge on Google group claco-dev about it. The
>> trick works.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/claroline/Claroline/issues/655#issuecomment-76682494>
>> .
>>
>
>
>
> --
> Godfraind Nicolas
> 5, rue de la Carrière
> 6592 Monceau-Imbrechies
> GSM: 0472 94 80 99
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
Update claroline/bundle-recorder, then you can update composer and
everything should be fine.

2015-03-02 16:45 GMT+01:00 Godfraind Nicolas <nicolas.godfraind@gmail.com>:

> Ok it's not a bug, but PackageEvent parent's class changed. The same goes
> for a lot of other stuff wich is why everything broke.
> I can fix it now.
>
> 2015-03-02 16:14 GMT+01:00 Godfraind Nicolas <nicolas.godfraind@gmail.com>
> :
>
>> I think it is a composer bug introduced by this commit
>> https://github.com/composer/composer/commit/3efed220a6c9fd6e4a13ea806879e124941c9fc7#diff-c2d55809c84c01df1b142806afcc20de
>> .
>>
>>
>>
>> 2015-03-02 10:39 GMT+01:00 stmolivier <notifications@github.com>:
>>
>>> yes, i've just seen the messsge on Google group claco-dev about it. The
>>> trick works.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/claroline/Claroline/issues/655#issuecomment-76682494>
>>> .
>>>
>>
>>
>>
>> --
>> Godfraind Nicolas
>> 5, rue de la Carrière
>> 6592 Monceau-Imbrechies
>> GSM: 0472 94 80 99
>>
>
>
>
> --
> Godfraind Nicolas
> 5, rue de la Carrière
> 6592 Monceau-Imbrechies
> GSM: 0472 94 80 99
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99
