### ISSUE TITLE
Bug : configuration of workspace tool publicly available

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#657]
On Claroline 4.2.2
There is a critical bug  : anyone, knowing the path can access directly the administrator page allowing the tools for the personnal workspace
[site]/web/app.php/admin/users/workspace/personal/tool/config

That anonymous can't change anything, but can see the allowed configuration.

**Comment by ngodfraind** [comment]
Thanks for the report. I'm going to fix that.

2015-03-01 21:56 GMT+01:00 stmolivier <notifications@github.com>:

> On Claroline 4.2.2
> There is a critical bug : anyone, knowing the path can access directly the
> administrator page allowing the tools for the personnal workspace
> [site]/web/app.php/admin/users/workspace/personal/tool/config
>
> That anonymous can't change anything, but can see the allowed
> configuration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/657>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
Fixed by claroline/CoreBundle#1041
