### ISSUE TITLE
Bug or not ? mp3 not readable

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#662]
I've read a (old ?) documentation on Claroline Connect https://docs.google.com/document/d/1WGNFKRVqEFF1bX7PmA6Xr5GjeQxBXklcVq0qV4u_G_U/edit 
and p14, it says there is a mp3 player when integrating a mp3 in a text ressource. I tested it with a light mp3 (300k, just in case) but i can only download it.
I tested it on Chrome and Iceweasel (debian).
* Is it the expected action or not ? (no more mp3 player)
* What are the readable media mimetypes included ? 
 * For video, I've successfully integrated mp4, webm, ogv in the text for video; but mov, avi won't play. flv crashes.
 * For audio : mp3 and ogg won"t play
 * for text : pdf is completely integrated. But doc, docx, ppt... and all M$ documents are only downloadable, even with browser integration.

**Comment by ngodfraind** [comment]
For now we're using the html player and it doesn't read everything. We
planned to use a flash one instead but we had no time to do it yet.
There is a pdf player but we didn't do anything for ms documents.

2015-03-04 16:24 GMT+01:00 stmolivier <notifications@github.com>:

> I've read a (old ?) documentation on Claroline Connect
> https://docs.google.com/document/d/1WGNFKRVqEFF1bX7PmA6Xr5GjeQxBXklcVq0qV4u_G_U/edit
> and p14, it says there is a mp3 player when integrating a mp3 in a text
> ressource. I tested it with a light mp3 (300k, just in case) but i can only
> download it.
> I tested it on Chrome and Iceweasel (debian).
>
>    - Is it the expected action or not ? (no more mp3 player)
>    - What are the readable media mimetypes included ?
>       - For video, I've successfully integrated mp4, webm, ogv in the
>       text for video; but mov, avi won't play. flv crashes.
>       - For audio : mp3 and ogg won"t play
>       - for text : pdf is completely integrated. But doc, docx, ppt...
>       and all M$ documents are only downloadable, even with browser integration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/662>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
Thanks for the response. The mp4, webm and ogv are html5 standard so they are directly integrated. 
Flash player is ok for desk/laptop, but is a no-go for smart devices... 
But this is funny that standard mp3, which is also html5 <audio> is not automatically readable... 
I'll post in my next issue the dump of flv crash.
Thanks for the explaining.
