### ISSUE TITLE
Bug : flv upload crashes

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#663]
I tried to integrate different media with the text ressource and also with the file ressource : 
When i uploaded a flv file, i had this error : 
```
INFO - Matched route "claro_file_upload_with_tinymce" (parameters: "_controller": "Claroline\CoreBundle\Controller\FileController::uploadWithTinyMceAction", "parent": "3", "_route": "claro_file_upload_with_tinymce")
DEBUG - Read SecurityContext from the session

Error: ffmpeg_movie::getframe(): Frame number must be greater than zero in /home/olivier/www/claroline4-test1.com/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Utilities/ThumbnailCreator.php line 72
500 Internal Server Error - FatalErrorException

Stack Trace
in /home/olivier/www/claroline4-test1.com/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Utilities/ThumbnailCreator.php at line 72   -
        $media = new \ffmpeg_movie($originalPath);
        $frameCount = $media->getFrameCount();
        $frame = $media->getFrame(round($frameCount / 2));
        if ($frame) {
            $image = $frame->toGDImage();
```
I have installed ffmpeg...

**Comment by ngodfraind** [comment]
I'll dig into that, can you send me the video ?

2015-03-04 16:40 GMT+01:00 stmolivier <notifications@github.com>:

> I tried to integrate different media with the text ressource and also with
> the file ressource :
> When i uploaded a flv file, i had this error :
>
> INFO - Matched route "claro_file_upload_with_tinymce" (parameters: "_controller": "Claroline\CoreBundle\Controller\FileController::uploadWithTinyMceAction", "parent": "3", "_route": "claro_file_upload_with_tinymce")
> DEBUG - Read SecurityContext from the session
>
> Error: ffmpeg_movie::getframe(): Frame number must be greater than zero in /home/olivier/www/claroline4-test1.com/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Utilities/ThumbnailCreator.php line 72
> 500 Internal Server Error - FatalErrorException
>
> Stack Trace
> in /home/olivier/www/claroline4-test1.com/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Utilities/ThumbnailCreator.php at line 72   -
>         $media = new \ffmpeg_movie($originalPath);
>         $frameCount = $media->getFrameCount();
>         $frame = $media->getFrame(round($frameCount / 2));
>         if ($frame) {
>             $image = $frame->toGDImage();
>
> I have installed ffmpeg...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/663>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
I'm not sure how to send you the video, (mail, other ?) so i put it on github : 
https://github.com/stmolivier/test-one/blob/master/video.flv
It's a standard flv (FLV1 video + mp3 audio)
