### ISSUE TITLE
Installation fail (4.7)

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#669]
I tried to install the new version 4.7 with the script but I have errors. I'm printing all the steps i do : 

1 - i prepare a domain claro4git-1 
2 ```> mkdir ~/www/claroline/claro4git-1```
3 ```> cd ~/www/claroline/claro4git-1```
4 ```> curl -sS https://raw.githubusercontent.com/claroline/repository-scripts/master/install.sh | sh```
5a - If i do : 
```
> composer update --prefer-source
```
I have : 
```
Script Claroline\BundleRecorder\ScriptHandler::checkForPendingOperations handling the pre-update-cmd event terminated with an exception
                                     
[Exception]                                                            
A non empty operation file is already present (assumed not executed)
```
5b - So if i skip and do : 
```
> php app/console claroline:update
```
i have : 
```
Updating the platform...
[info] Checking database connection...
[info] Creating public sub-directories...
[info] Installing ClarolineCoreBundle...
[info] Launching pre-installation actions...
[info] Executing migrations...
[info] Loading required fixtures...
[info] Launching post-installation actions...
[info] Updating ClarolineCoreBundle info...
Dumping all dev assets.
Debug mode is on.

10:27:22 [dir+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/css/clarolinecore
10:27:22 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/css/clarolinecore/badge_picker.css
10:27:22 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/css/clarolinecore/badge.css
10:27:22 [dir+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/twbs/bootstrap/js
10:27:22 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/twbs/bootstrap/js/bootstrap.js
10:27:22 [dir+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/jms/twig-js
10:27:22 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/jms/twig-js/twig.js
10:27:22 [dir+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/js
10:27:22 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/js/c256779.en.js
10:27:23 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/js/c256779.fr.js
10:27:24 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/js/c256779.es.js
10:27:25 [dir+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/jquery/ui
10:27:25 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/jquery/ui/jqueryui.js
                                                                                          
[RuntimeException]                                                                                                                                                       
  The source file "/home/olivier/www/claroline/claro4git-1/Claroline/app/../web/bundles/frontend/jquery/jquery-ui-1.9.2/components/jquery.ui.core.min.js" does not exist.  
```
5c - if i insist and 
* ```> php app/console claroline:user:create -a ```
* ```> chmod -R 775 app/cache/ app/sessions/ app/logs/ app/config/ web/uploads/ templates/ files/ ```
* ```> sudo chown -hR www-data:www-data ~/www/claroline/claro4git-1```

In my browser i do ```http://claro4git-1/web/app_dep.php```
i have a "broken" homepage
displaying : 
```
/Claroline/web/app_dev.php/
http://claro4git-1/Claroline/web/
en
Veuillez patienter...
Espaces d'activités
Tous les espaces d'activités publics
Connexion
Inscription
Connexion
FR Développé par Claroline (v4.7.0)
```
Did i miss a step or did i misunderstood the curl script  ? To me it replaces : 
* ```> git clone https://github.com/claroline/Claroline.git```
* creation of app/config/parameters.yml
* ```> composer require composer/composer dev-master```
* ```> composer require claroline/bundle-recorder "~4.0"```
* ```> cp composer.json.min composer.json```

**Comment by ngodfraind** [comment]
I'll look at it, it looks like some jquery components are missing.

2015-03-22 11:47 GMT+01:00 stmolivier <notifications@github.com>:

> I tried to install the new version 4.7 with the script but I have errors.
> I'm printing all the steps i do :
>
> 1 - i prepare a domain claro4git-1
> 2 > mkdir ~/www/claroline/claro4git-1
> 3 > cd ~/www/claroline/claro4git-1
> 4 > curl -sS
> https://raw.githubusercontent.com/claroline/repository-scripts/master/install.sh |
> sh
> 5a - If i do :
>
> > composer update --prefer-source
>
> I have :
>
> Script Claroline\BundleRecorder\ScriptHandler::checkForPendingOperations handling the pre-update-cmd event terminated with an exception
>
> [Exception]
> A non empty operation file is already present (assumed not executed)
>
> 5b - So if i skip and do :
>
> > php app/console claroline:update
>
> i have :
>
> Updating the platform...
> [info] Checking database connection...
> [info] Creating public sub-directories...
> [info] Installing ClarolineCoreBundle...
> [info] Launching pre-installation actions...
> [info] Executing migrations...
> [info] Loading required fixtures...
> [info] Launching post-installation actions...
> [info] Updating ClarolineCoreBundle info...
> Dumping all dev assets.
> Debug mode is on.
>
> 10:27:22 [dir+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/css/clarolinecore
> 10:27:22 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/css/clarolinecore/badge_picker.css
> 10:27:22 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/css/clarolinecore/badge.css
> 10:27:22 [dir+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/twbs/bootstrap/js
> 10:27:22 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/twbs/bootstrap/js/bootstrap.js
> 10:27:22 [dir+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/jms/twig-js
> 10:27:22 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/jms/twig-js/twig.js
> 10:27:22 [dir+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/js
> 10:27:22 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/js/c256779.en.js
> 10:27:23 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/js/c256779.fr.js
> 10:27:24 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/js/c256779.es.js
> 10:27:25 [dir+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/jquery/ui
> 10:27:25 [file+] /home/olivier/www/claroline/claro4git-1/Claroline/app/../web/vendor/jquery/ui/jqueryui.js
>
> [RuntimeException]
>   The source file "/home/olivier/www/claroline/claro4git-1/Claroline/app/../web/bundles/frontend/jquery/jquery-ui-1.9.2/components/jquery.ui.core.min.js" does not exist.
>
> 5c - if i insist and
>
>    - > php app/console claroline:user:create -a
>    - > chmod -R 775 app/cache/ app/sessions/ app/logs/ app/config/
>    web/uploads/ templates/ files/
>    - > sudo chown -hR www-data:www-data ~/www/claroline/claro4git-1
>
> In my browser i do http://claro4git-1/web/app_dep.php
> i have a "broken" homepage
> displaying :
>
> /Claroline/web/app_dev.php/http://claro4git-1/Claroline/web/
> en
> Veuillez patienter...
> Espaces d'activités
> Tous les espaces d'activités publics
> Connexion
> Inscription
> Connexion
> FR Développé par Claroline (v4.7.0)
>
> Did i miss a step or did i misunderstood the curl script ? To me it
> replaces :
>
>    - > git clone https://github.com/claroline/Claroline.git
>    - creation of app/config/parameters.yml
>    - > composer require composer/composer dev-master
>    - > composer require claroline/bundle-recorder "~4.0"
>    - > cp composer.json.min composer.json
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/669>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
ok great, it seemed like it indeed. Can you confirm if i use your script that i have to skip ```> composer update --prefer-source```
Sorry for the bad sunday report

**Comment by ngodfraind** [comment]
I'll just remove the operation files. It'll be better that way.

2015-03-22 11:57 GMT+01:00 stmolivier <notifications@github.com>:

> ok great, it seemed like it indeed. Can you confirm if i use your script
> that i have to skip > composer update --prefer-source
> Sorry for the bad sunday report
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/669#issuecomment-84587591>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
If i may ask, how come i seem to be the only one having trouble with the installation ? All the team working on the different bundle have to install or upgrade the Claroline core bundles i think. How do they do to avoid these troubles ?
