### ISSUE TITLE
claro 4.8 : error messag when bundle install 

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#670]
I just install this morning with : 
```
> curl -sS https://raw.githubusercontent.com/claroline/repository-scripts/master/install.sh | sh
> cd Claroline
> php app/console claroline:install
> php app/console assetic:dump
> php app/console assets:install --symlink
```
i then chmoded and rm -rf all cache and logs
Everyting when ok. 
I then logged in as administrator and went to Bundle management page to add the uninstall bundles : 
I click on install, The install log appears inthe modal and seems ok until completion. 
Then, before auto-closing, there's a popup coming up with the message : 
```
Whoops, looks like something went wrong.
1/1: Attempted to load class "ClarolineVideoPlayerBundle" from namespace "Claroline\VideoPlayerBundle" in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php line 55. Do you need to "use" it from another namespace?
1. in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php line 55

Fatal error: Class 'Claroline\VideoPlayerBundle\ClarolineVideoPlayerBundle' not found in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php on line 55
```
It's the same message for every bundle i install, but the ressources and tools "seems" to work properly.

Then, i logged off, logged in again and try to go back to the bundle management page, and i have the error : 
```
Warning: Invalid argument supplied for foreach() in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php line 98
500 Internal Server Error - 

Stack Trace
1. in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php at line 98  
95.         $installed = $this->getInstalled();
96.         $uninstalled = array();
97.         foreach ($bundles as $fetchedBundle) {
98.             $found = false;
99.             foreach ($installed as $bundle) {
100.                 if ($bundle->getName() === $fetchedBundle->name) {
```

**Comment by ngodfraind** [comment]
Thanks for the report.

2015-03-24 11:03 GMT+01:00 stmolivier <notifications@github.com>:

> I just install this morning with :
>
> > curl -sS https://raw.githubusercontent.com/claroline/repository-scripts/master/install.sh | sh
> > cd Claroline
> > php app/console claroline:install
> > php app/console assetic:dump
> > php app/console assets:install --symlink
>
> i then chmoded and rm -rf all cache and logs
> Everyting when ok.
> I then logged in as administrator and went to Bundle management page to
> add the uninstall bundles :
> I click on install, The install log appears inthe modal and seems ok until
> completion.
> Then, before auto-closing, there's a popup coming up with the message :
>
> Whoops, looks like something went wrong.
> 1/1: Attempted to load class "ClarolineVideoPlayerBundle" from namespace "Claroline\VideoPlayerBundle" in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php line 55. Do you need to "use" it from another namespace?
> 1. in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php line 55
>
> Fatal error: Class 'Claroline\VideoPlayerBundle\ClarolineVideoPlayerBundle' not found in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php on line 55
>
> It's the same message for every bundle i install, but the ressources and
> tools "seems" to work properly.
>
> Then, i logged off, logged in again and try to go back to the bundle
> management page, and i have the error :
>
> Warning: Invalid argument supplied for foreach() in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php line 98
> 500 Internal Server Error -
>
> Stack Trace
> 1. in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php at line 98
> 95.         $installed = $this->getInstalled();
> 96.         $uninstalled = array();
> 97.         foreach ($bundles as $fetchedBundle) {
> 98.             $found = false;
> 99.             foreach ($installed as $bundle) {
> 100.                 if ($bundle->getName() === $fetchedBundle->name) {
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/670>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
I've tested again: 
```> curl -sS https://raw.githubusercontent.com/claroline/repository-scripts/master/install.sh | sh```
OK
Then 
```> cd Claroline```
and 
```> php app/console claroline:update```

and i've got then : 
```
Updating the platform...
[info] Checking database connection...
[info] Creating public sub-directories...
Dumping all dev assets.
Debug mode is on.
                                                                     
  [Doctrine\DBAL\DBALException]                                                         
  An exception occurred while executing 'SELECT t0.id AS id1, t0.name AS name2, t0.pat  
  h AS path3, t0.plugin_id AS plugin_id4 FROM claro_theme t0':                          
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'claro4git-1.claro_theme'   
  doesn't exist                                                                         
                                                                                                                                                               
  [PDOException]                                                                        
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'claro4git-1.claro_theme'   
  doesn't exist                                                                         
                                                                                        
claroline:update
```

**Comment by ngodfraind** [comment]
php app/console doctrine:database:drop --force
php app/console doctrine:database:create
php app/console claroline:install

2015-03-29 19:28 GMT+02:00 stmolivier <notifications@github.com>:

> I've tested again:
> > curl -sS
> https://raw.githubusercontent.com/claroline/repository-scripts/master/install.sh |
> sh
> OK
> Then
> > cd Claroline
> and
> > php app/console claroline:update
>
> and i've got then :
>
> Updating the platform...
> [info] Checking database connection...
> [info] Creating public sub-directories...
> Dumping all dev assets.
> Debug mode is on.
>
>   [Doctrine\DBAL\DBALException]
>   An exception occurred while executing 'SELECT t0.id AS id1, t0.name AS name2, t0.pat
>   h AS path3, t0.plugin_id AS plugin_id4 FROM claro_theme t0':
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'claro4git-1.claro_theme'
>   doesn't exist
>
>   [PDOException]
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'claro4git-1.claro_theme'
>   doesn't exist
>
> claroline:update
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/670#issuecomment-87448664>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99
