### ISSUE TITLE
Claroline 4.9 - platform package error

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#673]
i've just installed C 4.9.0
```
> curl -sS https://raw.githubusercontent.com/claroline/repository-scripts/master/install.sh | sh
> cd Claroline
> php app/console doctrine:database:drop --force
> php app/console doctrine:database:create
> php app/console claroline:install
> php app/console claroline:user:create -a
> sudo chown www-data:www-data -R Claroline/
> sudo chmod -R 777 Claroline
> sudo php app/console assetic:dump
> sudo php app/console assets:install --symlink
> sudo rm -rf app/cache/*
```
The installation went smoothly :D 
i logged in as admin and everything i could try was working, but i tried to acces the platform package page to install resources and i got : 

```
Warning: Invalid argument supplied for foreach() in /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php line 98
500 Internal Server Error - ContextErrorException 

Stack Trace

1. in /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php at line 98  -
                $installed = $this->getInstalled();
                $uninstalled = array();
                foreach ($bundles as $fetchedBundle) {
                    $found = false;
                    foreach ($installed as $bundle) {
                        if ($bundle->getName() === $fetchedBundle->name) {
...
```

**Comment by ngodfraind** [comment]
Thanks for the report, I'll dig into that when I have some time.

2015-04-03 10:48 GMT+02:00 stmolivier <notifications@github.com>:

> i've just installed C 4.9.0
>
> > curl -sS https://raw.githubusercontent.com/claroline/repository-scripts/master/install.sh | sh
> > cd Claroline
> > php app/console doctrine:database:drop --force
> > php app/console doctrine:database:create
> > php app/console claroline:install
> > php app/console claroline:user:create -a
> > sudo chown www-data:www-data -R Claroline/
> > sudo chmod -R 777 Claroline
> > sudo php app/console assetic:dump
> > sudo php app/console assets:install --symlink
> > sudo rm -rf app/cache/*
>
> The installation went smoothly :D
> i logged in as admin and everything i could try was working, but i tried
> to acces the platform package page to install resources and i got :
>
> Warning: Invalid argument supplied for foreach() in /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php line 98
> 500 Internal Server Error - ContextErrorException
>
> Stack Trace
>
> 1. in /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php at line 98  -
>                 $installed = $this->getInstalled();
>                 $uninstalled = array();
>                 foreach ($bundles as $fetchedBundle) {
>                     $found = false;
>                     foreach ($installed as $bundle) {
>                         if ($bundle->getName() === $fetchedBundle->name) {
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/673>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
Just for info, i looked into the app/logs/dev.log and ssearch for error report and found these :
i don't know if it's related.
``` 
[2015-04-03 10:27:00] assetic.ERROR: The template "ClarolineMigrationBundle::migration_macros.html.twig" contains an error: The function "formatSql" does not exist in "ClarolineMigrationBundle::migration_macros.html.twig" at line 5
[2015-04-03 10:27:07] assetic.ERROR: The template "ZenstruckFormBundle:Twitter:grouped_form.html.twig" contains an error: The filter "slugify" does not exist in "ZenstruckFormBundle:Twitter:grouped_form.html.twig" at line 5
...
[2015-04-03 10:29:21] doctrine.DEBUG: SELECT t0.id AS id1, t0.name AS name2, t0.version AS version3, t0.type AS type4, t0.authors AS authors5, t0.description AS description6, t0.targetDir AS targetDir7, t0.basePath AS basePath8, t0.license AS license9, t0.isInstalled AS isInstalled10 FROM claro_bundle t0
[2015-04-03 10:29:21] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: Invalid argument supplied for foreach() in /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php line 98" at /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php line 98 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() in /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php line 98 at /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php:98)"}

```

**Comment by ngodfraind** [comment]
I'd say it's not related. I had similar errors before but I can't remember
how I fixed them (I think the fix was weird like a permission issue with
php-fpm or sthg).

2015-04-03 11:20 GMT+02:00 stmolivier <notifications@github.com>:

> Just for info, i looked into the app/logs/dev.log and ssearch for error
> report and found these :
> i don't know if it's related.
>
> [2015-04-03 10:27:00] assetic.ERROR: The template "ClarolineMigrationBundle::migration_macros.html.twig" contains an error: The function "formatSql" does not exist in "ClarolineMigrationBundle::migration_macros.html.twig" at line 5
> [2015-04-03 10:27:07] assetic.ERROR: The template "ZenstruckFormBundle:Twitter:grouped_form.html.twig" contains an error: The filter "slugify" does not exist in "ZenstruckFormBundle:Twitter:grouped_form.html.twig" at line 5
> ...
> [2015-04-03 10:29:21] doctrine.DEBUG: SELECT t0.id AS id1, t0.name AS name2, t0.version AS version3, t0.type AS type4, t0.authors AS authors5, t0.description AS description6, t0.targetDir AS targetDir7, t0.basePath AS basePath8, t0.license AS license9, t0.isInstalled AS isInstalled10 FROM claro_bundle t0
> [2015-04-03 10:29:21] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: Invalid argument supplied for foreach() in /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php line 98" at /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php line 98 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() in /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php line 98 at /home/user/www/claroline/claro4git-1/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php:98)"}
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/673#issuecomment-89234286>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
I tried again minutes ago : i can now access the page. But 
1 - i've got an error when installing the bundles (any of them)  : 
```
Whoops, looks like something went wrong.

1/1ClassNotFoundException: Attempted to load class "ClarolineWebResourceBundle" from namespace "Claroline\WebResourceBundle" in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php line 55. Do you need to "use" it from another namespace?
in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php line 55
```
2 - there is still no exercice bundle nor path bundle available : i've got only 
```
PdfPlayerBundle 4.0.0 
LdapBundle 4.0.0
WebResourceBundle 4.0.0
AnnouncementBundle 4.0.1
SurveyBundle 4.0.0
ScormBundle 4.0.0
ImagePlayerBundle 4.0.0
VideoPlayerBundle 4.0.0
RssReaderBundle 4.0.1
TeamBundle 4.0.1
ActivityToolBundle 4.0.0
ForumBundle 4.0.6
```

**Comment by ngodfraind** [comment]
Exercice bundle and Path bundle aren't available yet.


2015-04-03 21:01 GMT+02:00 stmolivier <notifications@github.com>:

> I tried again minutes ago : i can now access the page. But
> 1 - i've got an error when installing the bundles (any of them) :
>
> Whoops, looks like something went wrong.
>
> 1/1ClassNotFoundException: Attempted to load class "ClarolineWebResourceBundle" from namespace "Claroline\WebResourceBundle" in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php line 55. Do you need to "use" it from another namespace?
> in /home/olivier/www/claroline/claro4git-1/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php line 55
>
> 2 - there is still no exercice bundle nor path bundle available : i've got
> only
>
> PdfPlayerBundle 4.0.0
> LdapBundle 4.0.0
> WebResourceBundle 4.0.0
> AnnouncementBundle 4.0.1
> SurveyBundle 4.0.0
> ScormBundle 4.0.0
> ImagePlayerBundle 4.0.0
> VideoPlayerBundle 4.0.0
> RssReaderBundle 4.0.1
> TeamBundle 4.0.1
> ActivityToolBundle 4.0.0
> ForumBundle 4.0.6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/673#issuecomment-89392236>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
oh ok, i understand
