### ISSUE TITLE
Install error 4.10.0 Container.php on line 89

### ISSUE THREAD

**Issue by rafa62** [claroline/Claroline#675]
Hi,

I downloaded claroline-connect-4.10.0-full.zip from http://packages.claroline.net/releases/last-full.zip. I copied and decompressed, then I tried to run ../claroline/web/install.php. I got this error:

.../claroline/web/install.php 
PHP Fatal error:  Using $this when not in object context in .../claroline/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Container.php on line 89

How to fix this?

Best regads, Rafael.

**Comment by ngodfraind** [comment]
I'll look at it.

2015-04-13 20:10 GMT+02:00 rafa62 <notifications@github.com>:

> Hi,
>
> I downloaded claroline-connect-4.10.0-full.zip from
> http://packages.claroline.net/releases/last-full.zip. I copied and
> decompressed, then I tried to run ../claroline/web/install.php. I got this
> error:
>
> .../claroline/web/install.php
> PHP Fatal error: Using $this when not in object context in
> .../claroline/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Container.php
> on line 89
>
> How to fix this?
>
> Best regads, Rafael.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/675>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by marloncs** [comment]
hi there..

this error is for php version... you should be sure you are using php version 5.5 or lasted
