### ISSUE TITLE
Claroline (git install) not up-to-date

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#678]
Maybe the documentation is obsolete, but i installed a git version of Claroline with 
```
curl -sS https://raw.githubusercontent.com/claroline/repository-scripts/master/install.sh | sh
php app/console claroline:install
php app/console claroline:user:create -a
php app/console assetic:dump
php app/console assets:install --symlink
```
but i have a Claroline 4.12 installed, and not the last 5.x

Maybe it's because of the transition / heavy work you're doing. 
Do you suggest to get the zip file from the Claroline download section to test the Claroline 5 ?

**Comment by ngodfraind** [comment]
If you want I can update the script in order to install the 5.x but there
is still some weird unfixed bugs (probably because of the symfony2 upgrade)
and not every plugin is compatible yet.

2015-05-13 9:38 GMT+02:00 stmolivier <notifications@github.com>:

> Maybe the documentation is obsolete, but i installed a git version of
> Claroline with
>
> curl -sS https://raw.githubusercontent.com/claroline/repository-scripts/master/install.sh | sh
> php app/console claroline:install
> php app/console claroline:user:create -a
> php app/console assetic:dump
> php app/console assets:install --symlink
>
> but i have a Claroline 4.12 installed, and not the last 5.x
>
> Maybe it's because of the transition / heavy work you're doing.
> Do you suggest to get the zip file from the Claroline download section to
> test the Claroline 5 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/678>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
No problem, i can use the zip file until these issues are solved. This temporary phase is inevitable. Thank you for the update. I'll re-issue if i have issues with the [zip file](http://packages.claroline.net/releases/last-full.zip)
