### ISSUE TITLE
Installation script exception

### ISSUE THREAD

**Issue by pitrackster** [claroline/Claroline#681]
Hi !

There is a problem with the install command : 

```Argument 1 passed to Claroline\BundleRecorder\ScriptHandler::prepareUninstallOperation() must be an instance of Composer\Installer\PackageEvent, instance of Composer\Script\PackageEvent given, called in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php on line 207 and defined```

Thanks

**Comment by ngodfraind** [comment]
Hello,

Can you update composer and try again ?
composer self-update

2015-05-26 12:13 GMT+02:00 Guillou Patrick <notifications@github.com>:

> Hi !
>
> There is a problem with the install command :
>
> Argument 1 passed to
> Claroline\BundleRecorder\ScriptHandler::prepareUninstallOperation() must be
> an instance of Composer\Installer\PackageEvent, instance of
> Composer\Script\PackageEvent given, called in
> phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php
> on line 207 and defined
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/681>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by pitrackster** [comment]
Yep it works ! thanks !
