### ISSUE TITLE
Claroline through provisioning and just composer steps

### ISSUE THREAD

**Issue by bizmate** [claroline/Claroline#685]
Hi

as my previous comment, I noticed a number of things being done in a very specific way in Claroline, i.e. custom Kernel and installation through SH file instead of composer focused approach.

i.e. when installing Claroline through composer you end up with lots of packages but no clear way on how to install the application/bundles.

In this repo [Claroline with Vagrant/Puppet provisioning] (https://github.com/bizmate/caroline-provisioning) , you can use vagrant up (just vagrant and virtualbox required) to see what I mean.

From this base status could you suggest what a developer could do to add Claroline to its bundles and expose Controllers/Services/Run migrations etc? 

I am happy to help with PR if I get the point of the architecture. At the moment it is too overwhelming/complex to contribute.

**Comment by maxailloud** [comment]
JFYI Claroline is not a bundle, it's a LMS platform composed of multiple bundles.
You cannot add CLaroline to your bundle as Claroline is the application.

And we use a custom Kernel because of our plugin system we use to deal with plugin management.
And we use composer to get this plugin source and dependencies.

**Comment by bizmate** [comment]
I am not sure your statement above justifies the choice in architecture for your plugin system and my statement doesnt negate that caroline exposes resources and that they are valuable all together and not as separate bundles.

But claroline would have a greater value if its plugin system was decoupled from a custom controller implementation and it was just a series/collection of bundles that could be configured from a plain install of Symfony.

I personally was interested in Claroline by its survey package but then realised it was too much to take as it is not pluggable in a current application. Of course it is up to you in Claroline how you want to market/package the software but the current way is a monolithic piece that stops from deploying Claroline as a sub resource. Ultimately mine is just a contribution to show the obvious and what I think would add value. I hope it helps. Feel free to close the issue if unhelpful

**Comment by ngodfraind** [comment]
I agree that many claroline plugins would be valuable if it were possible
to use them in other symfony2 projects, but the application wasn't built in
a way that support it (as you noticed). Changing the way it works would
require a massive amount of work and I don't think it's realistic to do it
right now. Maybe one day we'll have some strong incentive to achieve this
goal, but it's far from our priority at this moment. I think you should
move on and not waste your time on this project (unless you're absolutely
sure you can somehow change what you want - in that case I'd be happy to
help you but it's not going to be easy as many weird side effects could
occur and many things are intricated; I'm not even sure it is possible to
do it).


2015-07-10 18:41 GMT+02:00 Diego Gullo <notifications@github.com>:

> I am not sure your statement above justifies the choice in architecture
> for your plugin system and my statement doesnt negate that caroline exposes
> resources and that they are valuable all together and not as separate
> bundles.
>
> But claroline would have a greater value if its plugin system was
> decoupled from a custom controller implementation and it was just a
> series/collection of bundles that could be configured from a plain install
> of Symfony.
>
> I personally was interested in Claroline by its survey package but then
> realised it was too much to take as it is not pluggable in a current
> application. Of course it is up to you in Claroline how you want to
> market/package the software but the current way is a monolithic piece that
> stops from deploying Claroline as a sub resource. Ultimately mine is just a
> contribution to show the obvious and what I think would add value. I hope
> it helps. Feel free to close the issue if unhelpful
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/685#issuecomment-120455183>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99
