### ISSUE TITLE
Claroline vs Claroline Connect

### ISSUE THREAD

**Issue by ywarnier** [claroline/Claroline#687]
Hi,
I believe this repo is for the Claroline Connect project, right? Shouldn't the README.md be a little more explicit about that? I was looking for the Claroline LMS repo (for v1.11) but I don't think this is the one...

**Comment by clarophil** [comment]
Hi,
The repo is on source forge http://sourceforge.net/projects/claroline/

**Comment by ywarnier** [comment]
Yes, I found it. That doesn't change the deep meaning of my issue... The README should really explain it's Claroline Connect.
