### ISSUE TITLE
Error log with many warning

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#690]
I've been looking the error log and i've got about 50 lines/second this  message : 
```
[Wed Aug 12 10:35:02 2015] [error] [client 10.209.0.14] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/user/web/monserveur.com/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/IPWhiteListManager.php on line 65, referer: http://monserveur.com/
```
This error apprears on every page i click. 

This is "only" a warning, but it's polluting the logs.

**Comment by ngodfraind** [comment]
Thanks for the report. I'll change that right now.

2015-08-12 10:55 GMT+02:00 stmolivier <notifications@github.com>:

> I've been looking the error log and i've got about 50 lines/second this
> message :
>
> [Wed Aug 12 10:35:02 2015] [error] [client 10.209.0.14] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/user/web/monserveur.com/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/IPWhiteListManager.php on line 65, referer: http://monserveur.com/
>
> This error apprears on every page i click.
>
> This is "only" a warning, but it's polluting the logs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/690>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
It should be fixed by Claroline/CoreBundle@469de9eb875e52d825008b2539d3ae6edbcfede2 but I didn't tried it.

**Comment by stmolivier** [comment]
i've done a "composer update" but it doesn't retrieve this correction from coreBundle (i've got version 5.1.11.4 from my platform_package info).
BTW, where in the bundle (here Corebundle) can i find it's version number (5.1.11.4 or whatever), it's not in the json ?

**Comment by ngodfraind** [comment]
I didn't tag anything yet iirc.

2015-08-14 10:01 GMT+02:00 stmolivier <notifications@github.com>:

> i've done a "composer update" but it doesn't retrieve this correction from
> coreBundle (i've got version 5.1.11.4 from my platform_package info).
> BTW, where in the bundle (here Corebundle) can i find it's version number
> (5.1.11.4 or whatever), it's not in the json ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/690#issuecomment-131011807>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stmolivier** [comment]
ok for that :)

**Comment by ngodfraind** [comment]
Fixed (a long time ago).
