### ISSUE TITLE
right access in V6 for personnal directory

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Claroline#696]
maybe i'm doing it wrong, but 
- i've created a administrator (with the cli)
- imported users

Each of them (admin and users) have personnal workspace. But neither can access the actions for the correspondig directory : 
![ws-rights](https://cloud.githubusercontent.com/assets/14015697/9926569/e68c61ee-5d16-11e5-8596-80729dd511e3.png)

Is it normal ? If so, it's counter intuitive : you have somewhere to set rights to your own directory.

**Comment by ngodfraind** [comment]
It is normal. Root directories can not be edited. But maybe not everything should be greyed.

**Comment by CPASimUSante** [comment]
OK, for root directory. But has it been discussed then to hide the unavailable options instead of greying them out ? It would be cleaner for the "casual" user ?

**Comment by ngodfraind** [comment]
Probably. We should talk about it in the claro-dev mailing list.
