### ISSUE TITLE
Improvement for user import

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Claroline#697]
I tried to import a list of user from a csv file and i had a error message saying one of my user had a problem in the mail. It appeard that in fact, there was an extra whitespace after the mail. Removing it, i managed to import the list : could you do a trim for such things ?

Another thing is that in import mode we can select one role (radio), but in a user we can select several (checkbox). Can't you permit several roles at creation ? It's tedious to edit every profile afterwards.

Thank you

**Comment by ngodfraind** [comment]
I'll fix that today.

2015-09-17 10:07 GMT+02:00 CPASimUSante <notifications@github.com>:

> I tried to import a list of user from a csv file and i had a error message
> saying one of my user had a problem in the mail. It appeard that in fact,
> there was an extra whitespace after the mail. Removing it, i managed to
> import the list : could you do a trim for such things ?
>
> Another thing is that in import mode we can select one role (radio), but
> in a user we can select several (checkbox). Can't you permit several roles
> at creation ? It's tedious to edit every profile afterwards.
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/697>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by CPASimUSante** [comment]
thank you

**Comment by ngodfraind** [comment]
Done on 5.x-stable
