### ISSUE TITLE
Twig error in topBarItems

### ISSUE THREAD

**Issue by clarophil** [claroline/Claroline#701]
Version 5.1.13
request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("") in 
\"/home/vinciv5/vendor/claroline/core-bundle/Claroline/CoreBundle/Resources/views/Layout/topBarItems.html.twig\" at line 24.
 at /home/vinciv5/app/cache/prod/classes.php:1746, Doctrine\\ORM\\NonUniqueResultException(code: 0):
  at /home/vinciv5/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:815)"} []

**Comment by ngodfraind** [comment]
Does it crash everything ?
It's the first time I ever see this error.
