### ISSUE TITLE
Long list of error in log (with FastCGI)

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Claroline#702]
A bit like https://github.com/claroline/Claroline/issues/690, i have this long list of error in my logs (i'm on 6.3.6) for my prod version :
```
Tue Sep 29 10:48:59 2015] [error] [client 127.0.0.1] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/user/web/claroline/web/app.php on line 26, referer: http://claroline.local/resource/open/file/59
[Tue Sep 29 10:49:00 2015] [error] [client 127.0.0.1] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/user/web/claroline/web/app.php on line 26, referer: http://claroline.local/desktop/tool/open/resource_manager?workspaceId=4?&
```

**Comment by ngodfraind** [comment]
This is something I noticed and fixed on the Claroline project. I did not
do any updater tho.
You can replace your app.php by the one on github to fix it.

2015-09-29 11:02 GMT+02:00 CPASimUSante <notifications@github.com>:

> A bit like #690 <https://github.com/claroline/Claroline/issues/690>, i
> have this long list of error in my logs (i'm on 6.3.6) for my prod version :
>
> Tue Sep 29 10:48:59 2015] [error] [client 127.0.0.1] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/user/web/claroline/web/app.php on line 26, referer: http://claroline.local/resource/open/file/59
> [Tue Sep 29 10:49:00 2015] [error] [client 127.0.0.1] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/user/web/claroline/web/app.php on line 26, referer: http://claroline.local/desktop/tool/open/resource_manager?workspaceId=4?&
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/702>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by CPASimUSante** [comment]
ok, will do. Thanks

**Comment by ngodfraind** [comment]
The next 5.x update will replace the file by the correct one.

**Comment by stmolivier** [comment]
OK, thanks. And the v6 will also have it, i presume ?

**Comment by ngodfraind** [comment]
Yes.

2015-10-08 10:57 GMT+02:00 stmolivier <notifications@github.com>:

> OK, thanks. And the v6 will also have it, i presume ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/702#issuecomment-146463092>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99
