### ISSUE TITLE
Bug : Error in plateform parameters

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Claroline#703]
On two different install, (v6.3.14)
Whe i'm administrator and go to admin/parameters/general  (the General page of administration)

I have this error : 
```
Notice: Undefined index: default_workspace_tag
500 Internal Server Error - ContextErrorException

Stack Trace
in vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Configuration/PlatformConfigurationHandler.php at line 201   -
        $config->setSendMailAtWorkspaceRegistration($this->parameters['send_mail_at_workspace_registration']);
        $config->setLocales($this->parameters['locales']);
        $config->setDomainName($this->parameters['domain_name']);
        $config->setDefaultWorkspaceTag($this->parameters['default_workspace_tag']);
        return $config;
    }
```

**Comment by ngodfraind** [comment]
Fixed by Claroline/CoreBundle@97e2ec45d431fad836ad15cad0ec9ba498b828da

**Comment by stmolivier** [comment]
OK. But to be sure : this commit is not in the latest version 6.3.14 ?
I did a ```composer update``` just before reporting it

**Comment by ngodfraind** [comment]
It currently is on the dev-master. It's not tagged yet.

2015-10-07 11:37 GMT+02:00 stmolivier <notifications@github.com>:

> OK. But to be sure : this commit is not in the latest version 6.3.14 ?
> I did a composer update just before reporting it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/703#issuecomment-146133014>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99
