### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by jmontoyaa** [claroline/Claroline#704]
When downloading:

http://packages.claroline.net/releases/last-full.zip

and following the instructions web/install.php I have this error:

```
[info] 10-08-15 12:07:36: Checking installation status for plugin InnovaPathBundle
[info] 10-08-15 12:07:36: Validating plugin...
[info] 10-08-15 12:07:36: Saving plugin configuration...
[info] 10-08-15 12:07:37: Installing InnovaPathBundle...
[info] 10-08-15 12:07:37: Launching pre-installation actions...
[info] 10-08-15 12:07:37: Executing migrations...
[ERROR] An exception has been thrown during installation
Message: An exception occurred while executing '
            ALTER TABLE innova_step_inherited_resources CHANGE resource_id resource_id INT NOT NULL, 
            CHANGE step_id step_id INT NOT NULL
        ':

SQLSTATE[HY000]: General error: 1832 Cannot change column 'step_id': used in a foreign key constraint 'FK_C7E87ECC73B21E9C'
Trace: #0 /var/www/html/claroline-connect-5.1.13-full/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/html/claroline-connect-5.1.13-full/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1027): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), '\n            AL...')
#2 /var/www/html/claroline-connect-5.1.13-full/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php(274): Doctrine\DBAL\Connection->exec('\n            AL...')
#3 /var/www/html/claroline-connect-5.1.13-full/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php(175): Doctrine\DBAL\Migrations\Version->execute('up', false, false)
#4 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Migrator/Migrator.php(98): Doctrine\DBAL\Migrations\Migration->migrate(NULL)
#5 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Manager/Manager.php(172): Claroline\MigrationBundle\Migrator\Migrator->migrate(Object(Innova\PathBundle\InnovaPathBundle), 'farthest', 'up')
#6 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Manager/Manager.php(98): Claroline\MigrationBundle\Manager\Manager->doMigrate(Object(Innova\PathBundle\InnovaPathBundle), 'farthest', 'up')
#7 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/installation-bundle/Claroline/InstallationBundle/Manager/InstallationManager.php(75): Claroline\MigrationBundle\Manager\Manager->upgradeBundle(Object(Innova\PathBundle\InnovaPathBundle), 'farthest')
#8 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Installation/Plugin/Installer.php(88): Claroline\InstallationBundle\Manager\InstallationManager->install(Object(Innova\PathBundle\InnovaPathBundle))
#9 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Installation/PlatformInstaller.php(126): Claroline\CoreBundle\Library\Installation\Plugin\Installer->install(Object(Innova\PathBundle\InnovaPathBundle))
#10 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(119): Claroline\CoreBundle\Library\Installation\PlatformInstaller->installFromKernel(false)
#11 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(63): Claroline\WebInstaller\Installer->launchInstaller(Object(appProdProjectContainer), Object(Symfony\Component\Console\Output\StreamOutput))
#12 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Controller.php(254): Claroline\WebInstaller\Installer->install()
#13 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Kernel.php(64): Claroline\WebInstaller\Controller->installSubmitStep()
#14 /var/www/html/claroline-connect-5.1.13-full/web/install.php(15): Claroline\WebInstaller\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#15 {main}
```

**Comment by ngodfraind** [comment]
The fix was accepted yesterday. I'll make a new release today with the fix.

2015-10-08 12:15 GMT+02:00 Julio <notifications@github.com>:

> When downloading:
>
> http://packages.claroline.net/releases/last-full.zip
>
> and following the instructions web/install.php I have this error:
>
> [info] 10-08-15 12:07:36: Checking installation status for plugin InnovaPathBundle
> [info] 10-08-15 12:07:36: Validating plugin...
> [info] 10-08-15 12:07:36: Saving plugin configuration...
> [info] 10-08-15 12:07:37: Installing InnovaPathBundle...
> [info] 10-08-15 12:07:37: Launching pre-installation actions...
> [info] 10-08-15 12:07:37: Executing migrations...
> [ERROR] An exception has been thrown during installation
> Message: An exception occurred while executing '
>             ALTER TABLE innova_step_inherited_resources CHANGE resource_id resource_id INT NOT NULL,
>             CHANGE step_id step_id INT NOT NULL
>         ':
>
> SQLSTATE[HY000]: General error: 1832 Cannot change column 'step_id': used in a foreign key constraint 'FK_C7E87ECC73B21E9C'
> Trace: #0 /var/www/html/claroline-connect-5.1.13-full/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
> #1 /var/www/html/claroline-connect-5.1.13-full/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1027): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), '\n            AL...')
> #2 /var/www/html/claroline-connect-5.1.13-full/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php(274): Doctrine\DBAL\Connection->exec('\n            AL...')
> #3 /var/www/html/claroline-connect-5.1.13-full/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php(175): Doctrine\DBAL\Migrations\Version->execute('up', false, false)
> #4 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Migrator/Migrator.php(98): Doctrine\DBAL\Migrations\Migration->migrate(NULL)
> #5 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Manager/Manager.php(172): Claroline\MigrationBundle\Migrator\Migrator->migrate(Object(Innova\PathBundle\InnovaPathBundle), 'farthest', 'up')
> #6 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Manager/Manager.php(98): Claroline\MigrationBundle\Manager\Manager->doMigrate(Object(Innova\PathBundle\InnovaPathBundle), 'farthest', 'up')
> #7 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/installation-bundle/Claroline/InstallationBundle/Manager/InstallationManager.php(75): Claroline\MigrationBundle\Manager\Manager->upgradeBundle(Object(Innova\PathBundle\InnovaPathBundle), 'farthest')
> #8 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Installation/Plugin/Installer.php(88): Claroline\InstallationBundle\Manager\InstallationManager->install(Object(Innova\PathBundle\InnovaPathBundle))
> #9 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Installation/PlatformInstaller.php(126): Claroline\CoreBundle\Library\Installation\Plugin\Installer->install(Object(Innova\PathBundle\InnovaPathBundle))
> #10 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(119): Claroline\CoreBundle\Library\Installation\PlatformInstaller->installFromKernel(false)
> #11 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(63): Claroline\WebInstaller\Installer->launchInstaller(Object(appProdProjectContainer), Object(Symfony\Component\Console\Output\StreamOutput))
> #12 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Controller.php(254): Claroline\WebInstaller\Installer->install()
> #13 /var/www/html/claroline-connect-5.1.13-full/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Kernel.php(64): Claroline\WebInstaller\Controller->installSubmitStep()
> #14 /var/www/html/claroline-connect-5.1.13-full/web/install.php(15): Claroline\WebInstaller\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
> #15 {main}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/704>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
Here is the commit of the fix:
InnovaLangues/PathBundle@c6830cbf0fc5bc407f2754f11d542209aae22457

**Comment by jmontoyaa** [comment]
:+1:

**Comment by ngodfraind** [comment]
5.1.14 is now released.
