### ISSUE TITLE
Error while installing a package  - Class 'ZipArchive' not found 

### ISSUE THREAD

**Issue by jmontoyaa** [claroline/Claroline#707]
I found this error in my apache error log:

I needed the zip extension, I resolved it using 

```
dnf install php-pecl-zip
```
in Fedora.

A message during the installation should warn this requirement.

```


[Thu Oct 08 14:01:26.107045 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP Fatal error:  Class 'ZipArchive' not found in /var/www/html/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php on line 181, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107067 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP Stack trace:, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107074 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP   1. {main}() /var/www/html/Claroline/web/app_dev.php:0, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107078 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP   2. Symfony\\Component\\HttpKernel\\Kernel->handle() /var/www/html/Claroline/web/app_dev.php:28, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107082 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP   3. Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle() /var/www/html/Claroline/app/bootstrap.php.cache:2444, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107086 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /var/www/html/Claroline/app/bootstrap.php.cache:3222, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107089 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /var/www/html/Claroline/app/bootstrap.php.cache:3071, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107092 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP   6. call_user_func_array:{/var/www/html/Claroline/app/bootstrap.php.cache:3109}() /var/www/html/Claroline/app/bootstrap.php.cache:3109, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107098 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP   7. EnhancedProxya64c872a_7afa02dedf1fc454e11fad278ca7e7c0ad9dd6f9\\__CG__\\Claroline\\CoreBundle\\Controller\\Administration\\PackageController->installFromRemoteAction() /var/www/html/Claroline/app/bootstrap.php.cache:3109, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107120 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP   8. CG\\Proxy\\MethodInvocation->proceed() /var/www/html/Claroline/app/cache/dev/jms_diextra/proxies/Claroline-CoreBundle-Controller-Administration-PackageController.php:66, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107125 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP   9. JMS\\SecurityExtraBundle\\Security\\Authorization\\Interception\\MethodSecurityInterceptor->intercept() /var/www/html/Claroline/vendor/jms/cg/src/CG/Proxy/MethodInvocation.php:79, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107132 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP  10. CG\\Proxy\\MethodInvocation->proceed() /var/www/html/Claroline/vendor/jms/security-extra-bundle/JMS/SecurityExtraBundle/Security/Authorization/Interception/MethodSecurityInterceptor.php:120, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107146 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP  11. ReflectionMethod->invokeArgs() /var/www/html/Claroline/vendor/jms/cg/src/CG/Proxy/MethodInvocation.php:84, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107152 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP  12. Claroline\\CoreBundle\\Controller\\Administration\\PackageController->installFromRemoteAction() /var/www/html/Claroline/vendor/jms/cg/src/CG/Proxy/MethodInvocation.php:84, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107166 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP  13. Claroline\\CoreBundle\\Manager\\BundleManager->installRemoteBundle() /var/www/html/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Controller/Administration/PackageController.php:170, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
[Thu Oct 08 14:01:26.107172 2015] [:error] [pid 21022] [client 127.0.0.1:51848] PHP  14. Claroline\\CoreBundle\\Manager\\BundleManager->installBundle() /var/www/html/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/BundleManager.php:124, referer: http://localhost/Claroline/web/app_dev.php/admin/package/


```

**Comment by ngodfraind** [comment]
This is true. Most of the time, php comes with the ZipArchive extension
included.
On a sidenode, the gui package update is not very stable yet. I suggest you
to use composer instead.

2015-10-08 14:18 GMT+02:00 Julio <notifications@github.com>:

> I found this error in my apache error log:
>
> I needed the zip extension, I resolved it using
>
> dnf install php-pecl-zip
>
> in Fedora.
>
> A message during the installation should warn this requirement.
>
>
>  PHP Fatal error:  Class 'Icap\\SocialmediaBundle\\IcapSocialmediaBundle' not found in /var/www/html/Claroline/vendor/claroline/kernel-bundle/Claroline/KernelBundle/Manager/BundleManager.php on line 55, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
> [Thu Oct 08 14:14:09.512310 2015] [:error] [pid 24414] [client 127.0.0.1:52378] PHP Stack trace:, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
> [Thu Oct 08 14:14:09.512328 2015] [:error] [pid 24414] [client 127.0.0.1:52378] PHP   1. {main}() /var/www/html/Claroline/web/app_dev.php:0, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
> [Thu Oct 08 14:14:09.512334 2015] [:error] [pid 24414] [client 127.0.0.1:52378] PHP   2. Symfony\\Component\\HttpKernel\\Kernel->handle() /var/www/html/Claroline/web/app_dev.php:28, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
> [Thu Oct 08 14:14:09.512339 2015] [:error] [pid 24414] [client 127.0.0.1:52378] PHP   3. Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle() /var/www/html/Claroline/app/bootstrap.php.cache:2444, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
> [Thu Oct 08 14:14:09.512345 2015] [:error] [pid 24414] [client 127.0.0.1:52378] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /var/www/html/Claroline/app/bootstrap.php.cache:3222, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
> [Thu Oct 08 14:14:09.512350 2015] [:error] [pid 24414] [client 127.0.0.1:52378] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /var/www/html/Claroline/app/bootstrap.php.cache:3071, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
> [Thu Oct 08 14:14:09.512373 2015] [:error] [pid 24414] [client 127.0.0.1:52378] PHP   6. Symfony\\Component\\HttpKernel\\HttpKernel->filterResponse() /var/www/html/Claroline/app/bootstrap.php.cache:3124, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
> [Thu Oct 08 14:14:09.512379 2015] [:error] [pid 24414] [client 127.0.0.1:52378] PHP   7. Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch() /var/www/html/Claroline/app/bootstrap.php.cache:3129, referer: http://localhost/Claroline/web/app_dev.php/admin/package/
> [Thu Oct 08 14:14:09.512394 2015] [:error] [pid 24414] [client 127.0.0.1:52378] PHP   8. Symfony\\Component\\
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/707>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99
