### ISSUE TITLE
Error when adding rss feed in widget

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#708]
On my prod server, (Claro v6.3.6) I've tried twice, with 2 different (working) rss feed : 
i create a widget, i select rss feed. It's ok. Then i add the feed, and i have the "please wait" message until the timeout, and Server error : 
```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator,and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
```
And in the log : 
- I have nothing in the app/log/prod.php for Claroline
- in the /var/log/appache2/error.log, i have nothing for it
- in the /var/log/appache2/myclaroline.log, i have : 
```
[Thu Oct 08 17:16:17 2015] [error] [client 127.0.0.1] FastCGI: comm with server "/usr/lib/cgi-bin/php5-fcgi" aborted: idle timeout (30 sec), referer: http://myclaroline.com/workspaces/1/open/tool/home/tab/5
[Thu Oct 08 17:16:17 2015] [error] [client 127.0.0.1] FastCGI: incomplete headers (0 bytes) received from server "/usr/lib/cgi-bin/php5-fcgi", referer: http://myclaroline.com/workspaces/1/open/tool/home/tab/5
```

This is problematic because, it causes the server to crash.
What could be causing this problem ?

**Comment by LaurentGruber** [comment]
This issue was moved to claroline/ClaroSupport#3
