### ISSUE TITLE
Bur (or not ?) : Personnal workspace visible in manage worspace

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Claroline#709]
When i want to create categories to manage the workspaces, i can see all workspaces, including all personnal workspace. Is that a but or is there a reason for that ? Since i can't access these (they are not public anyway), what is the use of displaying them ?

workspaces/workspace/tag/manage/page
Thanks

**Comment by LaurentGruber** [comment]
This issue was moved to claroline/ClaroSupport#4
