### ISSUE TITLE
Event object for 'open_tool_workspace_claroline_activity_tool' was not populated as expected

### ISSUE THREAD

**Issue by jmontoyaa** [claroline/Claroline#711]
After installing the platform and installing the plugins via GUI. 
I created a workspace and then I went to the activity tool:

and I have some errors when enter this URLs:

/Claroline/web/app_dev.php/workspaces/2/open/tool/claroline_activity_tool

Error:
<pre>
Event object for 'open_tool_workspace_claroline_activity_tool' was not populated as expected
</pre>

badges:

/Claroline/web/app_dev.php/workspaces/2/open/tool/badges

<pre>
Event object for 'open_tool_workspace_badges' was not populated as expected
</pre>

Just in case. This plugins are NOT installed in my platform:
<pre>
LdapBundle 5.0.1 Requirements failed for install
PortfolioBundle 5.1.2 Requirements failed for install
FacebookBundle 5.0.4 Requirements failed for install
PathBundle 5.3.13 Requirements failed for install
WikiBundle 5.1.1 Requirements failed for install
</pre>

**Comment by ngodfraind** [comment]
Did anything went wrong with the installation via GUI ?
