### ISSUE TITLE
Improvement : Add multiple roles in administration in user list

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Claroline#712]
As an administrator, I've created several users, but i forgot to create a specific role for them beforehand. So I create the role and then i want to give it to the users : i have to edit each one to add the role. There is a checkbox to select several user, but no button to assign role(s). It would be useful i think, as a platform administrator.

**Comment by LaurentGruber** [comment]
This issue was moved to claroline/ClaroSupport#6

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#65
