### ISSUE TITLE
Accès restreint par IP aux excercie

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Claroline#723]
@david42 @marion42 @charlotte42
Active un filtrage par plages d’IP ou seuls les postes contenus dans ces plages seront autorisés à répondre au questionnaire. Les autres verront un message leur interdisant l’accès, empêchant de voir les questions.
Le filtrage est utilisé pour des passages d’examens en salles de TP en présentiel.

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#64
