### ISSUE TITLE
Widget liste des ressources d'un tag

### ISSUE THREAD

**Issue by clarophil** [claroline/Claroline#729]
Il serait intéressant de disposer d'un widget permettant de lister les ressources qui ont un certain tag, par exemple j'ai tagué 2 fichiers, une vidéo et un forum "chapitre 1", dans l'onglet de l'espace je peux ajouter un widget qui listent toutes les ressources taguées chapitre 1, si je tague une nouvelle ressource elle vient s'ajouter au widget.

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#58
