### ISSUE TITLE
Amélioration de la gestion des droits

### ISSUE THREAD

**Issue by clarophil** [claroline/Claroline#733]
- Prévoir un  blocage des droits sur certains dossiers : dossier public, dossier caché

- Permettre un audit des droits, voir les droits pour un utilisateur sur une ressource

- Réinitialisation des droits : remettre les droits par défaut sur un dossier

- Afficher une icone sur la ressource si des droits particuliers sont définis

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#55
