### ISSUE TITLE
Partage de questions

### ISSUE THREAD

**Issue by marion42** [claroline/Claroline#777]
- Rajouter un message dans la suppression d'une question si elle est partagée + Revoir message suppression d'une question dans l'exo
- Partage global ( aujourd'hui on peut partager une question avec un utilisateur) Obj : pouvoir partager x questions avec x utilisateurs
- Suppression globale : suppression x questions
- Partager/Exporter sa banque complète

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#22
