### ISSUE TITLE
Intégration de la notation de Lyon

### ISSUE THREAD

**Issue by marion42** [claroline/Claroline#778]
Questions diverses 

Dans les QCM les "réponses attendues" sont floues car si l'on choisi l'option "point par question" on peut par exemple mettre -1 à une "réponse attendue". 

Types d'exercices :  
Passer un exercice sans notation (Formatif) 
Différent type de notation (Certificatif) :  
Moyenne sur 20 (actuellement), 
Notations rapide, chaque question vaudra la valeur [X] dans la note finale 
Sur [X] points (on ajoute les points des questions et on ne met pas sur 20 ce qui correspond au calcul pour les badges) 
Accepter les notes négatives pour les questions (options coché par défaut "pas de note finale 		négative") 
Utiliser d'autre système de notation (étoiles, lettres, en pourcentage...) 
Un barème  indépendant par question => voir détail * 
Les paliers pour le calcul général de la note : Permet de réajuster les notes. Par exemple: 
			Si l'apprenant a entre  0 et 5 questions  avec une note ≤ 0 ou avec une note > 			0, il obtiendra [X] points en note finale du questionnaire ou par question avec 			un score ≤ 0  
	Nota : Le questionnaire sera noté sur le total de points des questions. (points questionnaire 	= nombre de question * nombre de points par question) 

Intégrer la gestion des catégories dans les exercices => Pouvoir mettre que des questions d'une certaine catégorie dans une étape 
Pouvoir obliger l'étudiant à répondre à la question avant de passé à la page/étape suivante. 

Numéro de dossier :  
Pouvoir mettre un numéro de dossier sur une copie pour que l'étudiant puisse revenir sur sa copie en cours (pour des inscriptions par exemple, pour les utilisateurs qui n'ont pas de compte sur la plate-forme) 
Spécification de Lyon: 
Ce mode spécial du questionnaire permet de recharger une copie en cours ou déjà terminée, grâce à un numéro (alphanum) généré en fin de questionnaire. 
Il permet donc de recharger une copie de quelqu’un qui n’a pas de compte sur la plateforme, ou permet de remodifier une copie déjà terminée d’un répondant connecté. 
Ce mode est par exemple utilisé pour constituer des dossiers d’inscriptions d’utilisateurs n’ayant pas de compte sur la plateforme. 

Mode anonyme : 
Il faut mettre un flag sur la copie pour dire si elle a été passé en mode anonyme (pour la date de passage ne laisser apparaître que le mois et l'année) 
Prévenir l'étudiant au début de l'exercice qu'il passe un exercice en mode anonyme 

Création d’étapes/pages : 
Pouvoir générer aléatoirement des étapes avec un nombre maximum de questions aléatoires avec des règles 
Exemple : Je veux 10 questions par étapes sur mes 30 questions avec 2 en catégorie "Bio", 4 en catégorie "Cardio" et 6 en catégorie "Trauma" 

Publication de l'exercice : 
si l'étudiant a vu la correction, il n'a plus la possibilité de repasser l'exercice 
Restreindre l’accès d'un exercices avec un code ou l'adresse IP 

Affichage de la note : 
- Avoir la posssibilité de retarder le calcul de la note (si il y a un test avec 400 utilisateurs, ne pas calculer tout de suite les notes) Soit avoir un bouton pour calculer au moment que l'utilisateur veut (mais pb si le serveur est déjà surchargé) ou sinon programmer automatiquement le calcul pendant la nuit, pendant qu'il n'y a pas d'utilisateurs 
- Ne pas afficher la note si il y a besoin de faire une correction manuelle 

Partage des exercices "à tout le monde" : 
Passer d' un exercice sans être authentifié sur la plate-forme (ok en php, mais pas en Angular, voir avec Grenoble) 

* Notation exercice indépendant : 
QCM :  
Choix simple:  
- L'apprenant obtiendra tous les points de la question si il coche un choix juste. => En décochant "Attribuer les points par réponse", on fixe un nombre de points pour la réponse juste et un nombre de points pour la mauvaise réponse  
- Si l'apprenant coche un choix faux, il obtiendra [X]  points =>Avec la pondération par réponse on doit répond à cette demande 
Choix multiple: 
- L'apprenant doit cocher tous les choix justes, et ne cocher aucun choix faux pour obtenir les points de la question.  ===> En décochant "Attribuer les points par réponse" 
- L'apprenant verra sa note calculée selon son pourcentage de choix juste. 
- Par paliers :  
	Possibilité : L'apprenant ne doit cocher aucun choix faux pour avoir les 			points de la question 
Si l'apprenant a entre [X] et  [Y] , réponse fausse/juste,
Si l'apprenant toutes les réponse fausse/juste,
Si l'apprenant à plus [X] réponse fausse/juste,
Si l'apprenant à moins de [X] réponse fausse/juste,
								il obtiendra [Z] points en 	note finale pour la question ou par réponse fausses
- L'apprenant obtiendra les points cumulés des choix cochés. Ces points, positifs et négatifs. => Avec "Attribuer les points par réponse" on doit répond à cette demande 

Question à trous: 
- L'apprenant aura sa note calculée selon son pourcentage de bonne réponse 
- L'apprenant obtiendra les points cumulés de ses réponses (positifs et négatifs) => 	Fonctionnement de base 
- L'apprenant obtiendra [X] points si il donne une réponse qui n'est pas défini comme juste

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#20

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#23
