### ISSUE TITLE
Add view for Evaluation

### ISSUE THREAD

**Issue by ericvincenterv** [claroline/Claroline#779]
In "Collecticiel", we have the paramater "Evaluation".

If I choose this, we go to the view this 3 degrees : "Très bien", "Satisfaisant", "Insuffisant"

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#11

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#13

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#14

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#15

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#16

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#17

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#18

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#19

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#21
