### ISSUE TITLE
Improvement : Add multiple roles in administration in user list

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Claroline#781]
_From @LaurentGruber on March 23, 2016 12:35_

_From @CPASimUSante on October 26, 2015 17:23_

As an administrator, I've created several users, but i forgot to create a specific role for them beforehand. So I create the role and then i want to give it to the users : i have to edit each one to add the role. There is a checkbox to select several user, but no button to assign role(s). It would be useful i think, as a platform administrator.

_Copied from original issue: claroline/Claroline#712_

_Copied from original issue: claroline/ClaroSupport#6_

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#10

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#12
